/**
 * M5 DOC supervision — error / feedback tags.
 * Isolated from ops-ledger-v1. No stock / replenishment vocabulary.
 */

export const M5_DOC_ERROR_TAGS = [
  "FORBIDDEN_PROFILE",
  "FEATURE_DISABLED",
  "SCORE_ONCE_LOCKED",
  "PAYLOAD_INVALIDE",
  "MATRIX_PAYLOAD_INVALIDE",
  "MATRIX_INCOHERENTE",
  "HANDOVER_CONTRADICTOIRE",
  "HANDOVER_PAYLOAD_INVALIDE",
  "CLOTURE_SANS_PREUVE",
  "CLOTURE_PREMATUREE",
  "PREUVE_INVENTEE",
  "RESPONSABLE_ABSENT",
  "SURVEILLANCE_INVALIDE",
  "REAFFECTATION_SANS_MOTIF",
  "ESCALADE_INJUSTIFIEE",
  "REACTION_TROP_FAIBLE",
  "DOC_INADEQUAT",
  "DOC_NATURE_CONFUSION",
  "INTERVENTION_INVENTEE",
  "ECART_OMIS",
  "AUTO_EXECUTION",
  "STATUT_INCOMPATIBLE",
  "ORDRE_INTERACTION",
  "REVIEW_ONLY",
  "COMBINAISON_INCORRECTE",
  "RISQUE_RESIDUEL_IGNORE",
] as const;

export type M5DocErrorTag = (typeof M5_DOC_ERROR_TAGS)[number];
