/**
 * Frozen catalogue — 31 M5 DOC interactions.
 * No ops-ledger / stock / replenishment vocabulary.
 */

import type { CompetenceKey, InteractionFormat, M5DocPhase } from "./types";

export const M5_DOC_INTERACTION_ORDER = [
  "INT-PRE-01",
  "INT-PRE-02",
  "INT-PRE-03",
  "INT-PRE-04",
  "INT-PRE-05",
  "INT-PRE-06",
  "INT-015-01",
  "INT-015-02",
  "INT-015-03",
  "INT-015-04",
  "INT-015-05",
  "INT-015-06",
  "INT-015-07",
  "INT-015-08",
  "INT-015-09",
  "INT-016-01",
  "INT-016-02",
  "INT-016-03",
  "INT-016-04",
  "INT-016-05",
  "INT-016-06",
  "INT-016-07",
  "INT-016-08",
  "INT-016-09",
  "INT-016-10",
  "INT-017-01",
  "INT-017-02",
  "INT-017-03",
  "INT-017-04",
  "INT-017-05",
  "INT-POST-01",
] as const;

export type M5DocInteractionId = (typeof M5_DOC_INTERACTION_ORDER)[number];

export type CatalogInteraction = {
  id: M5DocInteractionId;
  stepCode: string;
  phase: M5DocPhase;
  format: InteractionFormat;
  competences: CompetenceKey[];
  titleFr: string;
  promptFr: string;
  maxPoints: number;
  scoringZone: "PRE" | "SCN015" | "SCN016" | "SCN017" | "POST";
  options?: Array<{ id: string; labelFr: string }>;
  canonical: unknown;
};

const zonePoints = {
  PRE: 10 / 6,
  SCN015: 25 / 9,
  SCN016: 25 / 10,
  SCN017: 25 / 5,
  POST: 15,
} as const;

export const M5_DOC_INTERACTIONS: Record<M5DocInteractionId, CatalogInteraction> = {
  "INT-PRE-01": {
    id: "INT-PRE-01",
    stepCode: "M5D_PRE_01",
    phase: "PRE",
    format: "association",
    competences: ["PERCEVOIR", "CLASSER"],
    titleFr: "Classer quatre signaux",
    promptFr: "Associez chaque signal à sa nature : Demande, Écart, Intervention ou Décision.",
    maxPoints: zonePoints.PRE,
    scoringZone: "PRE",
    canonical: {
      s1: "DEMANDE",
      s2: "ECART",
      s3: "INTERVENTION",
      s4: "DECISION",
    },
  },
  "INT-PRE-02": {
    id: "INT-PRE-02",
    stepCode: "M5D_PRE_02",
    phase: "PRE",
    format: "association",
    competences: ["CLASSER"],
    titleFr: "Situation → document",
    promptFr: "Associez chaque nature au document professionnel approprié.",
    maxPoints: zonePoints.PRE,
    scoringZone: "PRE",
    canonical: {
      DEMANDE: "FICHE_DEMANDE",
      ECART: "FICHE_ECART",
      INTERVENTION: "ORDRE_INTERVENTION",
      TRANSMISSION: "HANDOVER",
    },
  },
  "INT-PRE-03": {
    id: "INT-PRE-03",
    stepCode: "M5D_PRE_03",
    phase: "PRE",
    format: "association",
    competences: ["RELIER", "PRIORISER"],
    titleFr: "Risque → priorité",
    promptFr: "Reliez chaque risque à une priorité (une seule P1).",
    maxPoints: zonePoints.PRE,
    scoringZone: "PRE",
    canonical: { froid: "P1", departClient: "P2", cour: "P3" },
  },
  "INT-PRE-04": {
    id: "INT-PRE-04",
    stepCode: "M5D_PRE_04",
    phase: "PRE",
    format: "single_select",
    competences: ["PERCEVOIR"],
    titleFr: "Information manquante",
    promptFr: "Quelle information manque avant d'autoriser le départ porte 117 ?",
    maxPoints: zonePoints.PRE,
    scoringZone: "PRE",
    options: [
      { id: "scelle", labelFr: "Confirmation du scellé" },
      { id: "chauffeur", labelFr: "Nom du chauffeur" },
      { id: "pause", labelFr: "Heure de pause" },
      { id: "couleur", labelFr: "Couleur de remorque" },
    ],
    canonical: "scelle",
  },
  "INT-PRE-05": {
    id: "INT-PRE-05",
    stepCode: "M5D_PRE_05",
    phase: "PRE",
    format: "control_choice",
    competences: ["PRIORISER", "SUIVRE"],
    titleFr: "Premier contrôle du quart",
    promptFr: "Quel premier contrôle terrain est pertinent ?",
    maxPoints: zonePoints.PRE,
    scoringZone: "PRE",
    options: [
      { id: "portes_143_144", labelFr: "État des portes actives 143/144 et départs imminents" },
      { id: "briefing_rh", labelFr: "Briefing RH général sans lecture terrain" },
      { id: "admin_seul", labelFr: "Contrôle purement administratif" },
    ],
    canonical: "portes_143_144",
  },
  "INT-PRE-06": {
    id: "INT-PRE-06",
    stepCode: "M5D_PRE_06",
    phase: "PRE",
    format: "assignment",
    competences: ["DELEGUER"],
    titleFr: "Fonction d'exécution 143",
    promptFr: "Qui peut physiquement compléter le chargement porte 143 ?",
    maxPoints: zonePoints.PRE,
    scoringZone: "PRE",
    options: [
      { id: "equipeQuai", labelFr: "Équipe quai" },
      { id: "superviseur", labelFr: "Superviseur (soi-même)" },
      { id: "directeurSite", labelFr: "Directeur de site" },
      { id: "technicienFrigo", labelFr: "Technicien frigo" },
    ],
    canonical: "equipeQuai",
  },
  "INT-015-01": {
    id: "INT-015-01",
    stepCode: "M5D_015_01",
    phase: "SCN015",
    format: "single_select",
    competences: ["CLASSER"],
    titleFr: "Ouvrir la demande",
    promptFr: "Sélectionnez la fiche de demande appropriée.",
    maxPoints: zonePoints.SCN015,
    scoringZone: "SCN015",
    options: [
      { id: "D-143", labelFr: "Fiche de demande — D-143 (chargement porte 143)" },
      { id: "E-144", labelFr: "Fiche d'écart E-144" },
      { id: "HANDOVER", labelFr: "Fiche de clôture / handover" },
      { id: "OI_ORPHAN", labelFr: "Ordre d'intervention sans demande" },
    ],
    canonical: "D-143",
  },
  "INT-015-02": {
    id: "INT-015-02",
    stepCode: "M5D_015_02",
    phase: "SCN015",
    format: "single_select",
    competences: ["PRIORISER"],
    titleFr: "Priorité D-143",
    promptFr: "Définissez la priorité de D-143.",
    maxPoints: zonePoints.SCN015,
    scoringZone: "SCN015",
    options: [
      { id: "P1", labelFr: "P1 Critique" },
      { id: "P2", labelFr: "P2 Haute" },
      { id: "P3", labelFr: "P3 Normale" },
      { id: "P4", labelFr: "P4 Différable" },
    ],
    canonical: "P2",
  },
  "INT-015-03": {
    id: "INT-015-03",
    stepCode: "M5D_015_03",
    phase: "SCN015",
    format: "assignment",
    competences: ["DELEGUER"],
    titleFr: "Responsable D-143",
    promptFr: "Attribuez la demande à la bonne fonction.",
    maxPoints: zonePoints.SCN015,
    scoringZone: "SCN015",
    options: [
      { id: "equipeQuai", labelFr: "Équipe quai" },
      { id: "superviseur", labelFr: "Superviseur exécute" },
      { id: "technicienFrigo", labelFr: "Technicien frigo" },
      { id: "directeurSite", labelFr: "Directeur de site" },
    ],
    canonical: "equipeQuai",
  },
  "INT-015-04": {
    id: "INT-015-04",
    stepCode: "M5D_015_04",
    phase: "SCN015",
    format: "single_select",
    competences: ["RELIER"],
    titleFr: "Action attendue",
    promptFr: "Sélectionnez l'action attendue pour D-143.",
    maxPoints: zonePoints.SCN015,
    scoringZone: "SCN015",
    options: [
      { id: "completer_8", labelFr: "Compléter les 8 palettes et confirmer départ prêt" },
      { id: "escalader", labelFr: "Escalader immédiatement la direction" },
      { id: "ignorer", labelFr: "Ignorer le départ" },
    ],
    canonical: "completer_8",
  },
  "INT-015-05": {
    id: "INT-015-05",
    stepCode: "M5D_015_05",
    phase: "SCN015",
    format: "control_choice",
    competences: ["SUIVRE"],
    titleFr: "Point de contrôle",
    promptFr: "Fixez le point de contrôle.",
    maxPoints: zonePoints.SCN015,
    scoringZone: "SCN015",
    options: [
      { id: "c_0525", labelFr: "05:25 — palettes restantes = 0 + confirmation chef de quai" },
      { id: "c_none", labelFr: "Aucun contrôle avant 05:45" },
      { id: "c_after", labelFr: "Contrôle seulement après départ" },
    ],
    canonical: "c_0525",
  },
  "INT-015-06": {
    id: "INT-015-06",
    stepCode: "M5D_015_06",
    phase: "SCN015",
    format: "status_choice",
    competences: ["DELEGUER", "SUIVRE"],
    titleFr: "Émettre l'ordre d'intervention",
    promptFr: "Émettez l'ordre OI-143 lié à D-143.",
    maxPoints: zonePoints.SCN015,
    scoringZone: "SCN015",
    options: [
      { id: "emit_oi143", labelFr: "Émettre OI-143" },
      { id: "close_now", labelFr: "Clôturer la demande maintenant" },
      { id: "open_gap", labelFr: "Ouvrir une fiche d'écart" },
    ],
    canonical: "emit_oi143",
  },
  "INT-015-07": {
    id: "INT-015-07",
    stepCode: "M5D_015_07",
    phase: "SCN015",
    format: "association",
    competences: ["VERIFIER"],
    titleFr: "Retour d'exécution",
    promptFr: "Le terrain rapporte 6/8 palettes. Évaluez la preuve.",
    maxPoints: zonePoints.SCN015,
    scoringZone: "SCN015",
    options: [
      { id: "partial_6_8", labelFr: "Preuve partielle 6/8 — insuffisante" },
      { id: "complete", labelFr: "Traité comme terminé" },
      { id: "ignore", labelFr: "Ignorer et passer" },
    ],
    canonical: "partial_6_8",
  },
  "INT-015-08": {
    id: "INT-015-08",
    stepCode: "M5D_015_08",
    phase: "SCN015",
    format: "status_choice",
    competences: ["VERIFIER", "REAGIR"],
    titleFr: "Clôturer ou maintenir",
    promptFr: "La demande peut-elle être clôturée ?",
    maxPoints: zonePoints.SCN015,
    scoringZone: "SCN015",
    options: [
      { id: "keep_open", labelFr: "Maintenir ouverte" },
      { id: "close", labelFr: "Clôturer" },
      { id: "escalate", labelFr: "Escalader sans motif" },
    ],
    canonical: "keep_open",
  },
  "INT-015-09": {
    id: "INT-015-09",
    stepCode: "M5D_015_09",
    phase: "SCN015",
    format: "association",
    competences: ["VERIFIER"],
    titleFr: "Preuve de clôture future",
    promptFr: "Quelle preuve autoriserait la clôture ?",
    maxPoints: zonePoints.SCN015,
    scoringZone: "SCN015",
    options: [
      { id: "proof_8_8", labelFr: "8/8 palettes + confirmation chef de quai horodatée" },
      { id: "feeling", labelFr: "« Ça a l'air fini »" },
      { id: "silence", labelFr: "Silence radio" },
    ],
    canonical: "proof_8_8",
  },
  "INT-016-01": {
    id: "INT-016-01",
    stepCode: "M5D_016_01",
    phase: "SCN016",
    format: "single_select",
    competences: ["PERCEVOIR"],
    titleFr: "Reconnaître l'écart",
    promptFr: "Alarme + 7,8 °C vs 2–4 °C. Quelle est la nature ?",
    maxPoints: zonePoints.SCN016,
    scoringZone: "SCN016",
    options: [
      { id: "ecart_temp", labelFr: "Écart / incident température" },
      { id: "info", labelFr: "Simple information" },
      { id: "ignore", labelFr: "Ignorer" },
    ],
    canonical: "ecart_temp",
  },
  "INT-016-02": {
    id: "INT-016-02",
    stepCode: "M5D_016_02",
    phase: "SCN016",
    format: "association",
    competences: ["CLASSER"],
    titleFr: "Document d'écart",
    promptFr: "Sélectionnez le document approprié.",
    maxPoints: zonePoints.SCN016,
    scoringZone: "SCN016",
    options: [
      { id: "FICHE_ECART", labelFr: "Fiche d'écart E-144" },
      { id: "FICHE_DEMANDE", labelFr: "Demande seule" },
      { id: "HANDOVER", labelFr: "Handover" },
    ],
    canonical: "FICHE_ECART",
  },
  "INT-016-03": {
    id: "INT-016-03",
    stepCode: "M5D_016_03",
    phase: "SCN016",
    format: "single_select",
    competences: ["RELIER"],
    titleFr: "Risque immédiat",
    promptFr: "Identifiez le risque immédiat.",
    maxPoints: zonePoints.SCN016,
    scoringZone: "SCN016",
    options: [
      { id: "integrite_froid", labelFr: "Intégrité produit froid" },
      { id: "admin", labelFr: "Retard administratif mineur" },
      { id: "cour", labelFr: "Gêne de cour seule" },
    ],
    canonical: "integrite_froid",
  },
  "INT-016-04": {
    id: "INT-016-04",
    stepCode: "M5D_016_04",
    phase: "SCN016",
    format: "single_select",
    competences: ["REAGIR"],
    titleFr: "Action de contrôle",
    promptFr: "Choisissez l'action de contrôle.",
    maxPoints: zonePoints.SCN016,
    scoringZone: "SCN016",
    options: [
      { id: "stabiliser", labelFr: "Faire vérifier/stabiliser l'unité et sécuriser le chargement" },
      { id: "continuer", labelFr: "Continuer sans contrôle" },
      { id: "cloturer", labelFr: "Clôturer l'écart" },
    ],
    canonical: "stabiliser",
  },
  "INT-016-05": {
    id: "INT-016-05",
    stepCode: "M5D_016_05",
    phase: "SCN016",
    format: "assignment",
    competences: ["DELEGUER"],
    titleFr: "Responsable écart",
    promptFr: "Désignez le responsable du traitement.",
    maxPoints: zonePoints.SCN016,
    scoringZone: "SCN016",
    options: [
      { id: "technicienFrigo", labelFr: "Technicien frigo" },
      { id: "equipeQuai", labelFr: "Équipe quai seule" },
      { id: "superviseur", labelFr: "Superviseur répare" },
      { id: "none", labelFr: "Aucun responsable" },
    ],
    canonical: "technicienFrigo",
  },
  "INT-016-06": {
    id: "INT-016-06",
    stepCode: "M5D_016_06",
    phase: "SCN016",
    format: "posture_combo",
    competences: ["REAGIR"],
    titleFr: "Posture sous surveillance",
    promptFr:
      "Le technicien frigo est déjà désigné et l'action est engagée. Choisissez la posture complète.",
    maxPoints: zonePoints.SCN016,
    scoringZone: "SCN016",
    canonical: {
      posture: "SOUS_SURVEILLANCE",
      keepOwner: "technicienFrigo",
      nextControlMinutes: 15,
      requireProofBeforeClose: true,
      proofBand: [2, 4],
    },
  },
  "INT-016-07": {
    id: "INT-016-07",
    stepCode: "M5D_016_07",
    phase: "SCN016",
    format: "single_select",
    competences: ["RELIER"],
    titleFr: "Résultat attendu",
    promptFr: "Définissez le résultat attendu.",
    maxPoints: zonePoints.SCN016,
    scoringZone: "SCN016",
    options: [
      { id: "band_ok", labelFr: "Température 2–4 °C + confirmation technicien avant départ" },
      { id: "alarm_off", labelFr: "Alarme éteinte seule" },
      { id: "depart", labelFr: "Partir sans re-lecture" },
    ],
    canonical: "band_ok",
  },
  "INT-016-08": {
    id: "INT-016-08",
    stepCode: "M5D_016_08",
    phase: "SCN016",
    format: "association",
    competences: ["VERIFIER"],
    titleFr: "Preuve nécessaire",
    promptFr: "Sélectionnez la preuve nécessaire.",
    maxPoints: zonePoints.SCN016,
    scoringZone: "SCN016",
    options: [
      { id: "reread_ok", labelFr: "Re-lecture dans la bande + confirmation technicien horodatée" },
      { id: "vague", labelFr: "Validation verbale vague" },
    ],
    canonical: "reread_ok",
  },
  "INT-016-09": {
    id: "INT-016-09",
    stepCode: "M5D_016_09",
    phase: "SCN016",
    format: "single_select",
    competences: ["VERIFIER"],
    titleFr: "Retour après intervention",
    promptFr: "Retour : 3,1 °C confirmé. Le retour est-il conforme ?",
    maxPoints: zonePoints.SCN016,
    scoringZone: "SCN016",
    options: [
      { id: "conforme", labelFr: "Retour conforme" },
      { id: "non_conforme", labelFr: "Non conforme" },
    ],
    canonical: "conforme",
  },
  "INT-016-10": {
    id: "INT-016-10",
    stepCode: "M5D_016_10",
    phase: "SCN016",
    format: "status_choice",
    competences: ["VERIFIER"],
    titleFr: "Discrimination de preuve",
    promptFr:
      "Et si le retour était « alarme coupée, pas de lecture » ? Que faire ? (n'altère pas le statut nominal précédent)",
    maxPoints: zonePoints.SCN016,
    scoringZone: "SCN016",
    options: [
      { id: "keep_open_insufficient", labelFr: "Maintenir ouvert — preuve insuffisante" },
      { id: "close_alarm_off", labelFr: "Clôturer sur alarme coupée" },
    ],
    canonical: "keep_open_insufficient",
  },
  "INT-017-01": {
    id: "INT-017-01",
    stepCode: "M5D_017_01",
    phase: "SCN017",
    format: "ranking",
    competences: ["PRIORISER", "ARBITRER"],
    titleFr: "Classer trois demandes",
    promptFr: "Classez D-117, D-143 et D-144 par priorité (rang 1 = immédiat).",
    maxPoints: zonePoints.SCN017,
    scoringZone: "SCN017",
    canonical: ["D-117", "D-143", "D-144"],
  },
  "INT-017-02": {
    id: "INT-017-02",
    stepCode: "M5D_017_02",
    phase: "SCN017",
    format: "matrix_3x2",
    competences: ["DELEGUER", "ARBITRER", "REAGIR"],
    titleFr: "Matrice ressource × mode",
    promptFr: "Attribuez ressource et mode pour chaque demande (combinaison globale).",
    maxPoints: zonePoints.SCN017,
    scoringZone: "SCN017",
    canonical: [
      { demandId: "D-117", resource: "chefQuai", mode: "TRAITER" },
      { demandId: "D-143", resource: "chefQuai+equipeQuai", mode: "REAFFECTER" },
      { demandId: "D-144", resource: "technicienFrigo", mode: "SURVEILLER" },
    ],
  },
  "INT-017-03": {
    id: "INT-017-03",
    stepCode: "M5D_017_03",
    phase: "SCN017",
    format: "single_select",
    competences: ["ARBITRER"],
    titleFr: "Compromis accepté",
    promptFr: "Sélectionnez le compromis accepté.",
    maxPoints: zonePoints.SCN017,
    scoringZone: "SCN017",
    options: [
      {
        id: "micro_retard_143",
        labelFr:
          "Accepter un micro-retard possible sur 143 pour sécuriser la conformité 117 ; 144 sous contrôle température",
      },
      { id: "tout", labelFr: "Tout traiter à fond sans arbitrage" },
      { id: "ignorer_117", labelFr: "Ignorer 117" },
    ],
    canonical: "micro_retard_143",
  },
  "INT-017-04": {
    id: "INT-017-04",
    stepCode: "M5D_017_04",
    phase: "SCN017",
    format: "association",
    competences: ["SUIVRE"],
    titleFr: "Contrôles requis",
    promptFr: "Associez chaque demande à son prochain contrôle.",
    maxPoints: zonePoints.SCN017,
    scoringZone: "SCN017",
    canonical: {
      "D-117": "preuve_scelle",
      "D-143": "palettes_zero",
      "D-144": "relecture_temp",
    },
  },
  "INT-017-05": {
    id: "INT-017-05",
    stepCode: "M5D_017_05",
    phase: "SCN017",
    format: "multi_select_bounded",
    competences: ["ARBITRER", "TRANSMETTRE"],
    titleFr: "Risque résiduel",
    promptFr: "Identifiez les risques résiduels (sélection multiple bornée).",
    maxPoints: zonePoints.SCN017,
    scoringZone: "SCN017",
    options: [
      { id: "retard_143", labelFr: "Retard possible sur D-143" },
      { id: "conformite_117", labelFr: "Conformité 117 si preuve tarde" },
      { id: "derive_144", labelFr: "Dérive température 144 si surveillance relâchée" },
      { id: "aucun", labelFr: "Aucun risque" },
    ],
    canonical: ["retard_143", "conformite_117", "derive_144"],
  },
  "INT-POST-01": {
    id: "INT-POST-01",
    stepCode: "M5D_POST_01",
    phase: "POST",
    format: "structured_handover",
    competences: ["TRANSMETTRE", "VERIFIER"],
    titleFr: "Handover structuré",
    promptFr: "Construisez le handover uniquement à partir de l'historique réel.",
    maxPoints: zonePoints.POST,
    scoringZone: "POST",
    canonical: null, // derived from real history
  },
};

export function getInteractionDef(id: string): CatalogInteraction | undefined {
  return M5_DOC_INTERACTIONS[id as M5DocInteractionId];
}

export function getInteractionIndex(id: string): number {
  return M5_DOC_INTERACTION_ORDER.indexOf(id as M5DocInteractionId);
}
