import type { DepartmentCode, PriorityLevel, ScenarioUniverseBinding } from "../enterpriseBriefing";

/** Scenario-to-universe binding — Enterprise Universe Part XII */
export const SCENARIO_UNIVERSE_BINDINGS: Record<string, ScenarioUniverseBinding> = {
  "SCN-001": {
    scnCode: "SCN-001",
    businessUnit: "BU-DIST",
    customerCode: "C-PAPI",
    supplierCode: "S-STLA",
    warehouseZone: "REC → B → EXP",
    incidentId: null,
    supervisorId: "marc-andre-tremblay",
    priority: "normal",
    department: "REC",
  },
  "SCN-002": {
    scnCode: "SCN-002",
    businessUnit: "BU-DIST",
    customerCode: null,
    supplierCode: "S-STLA",
    warehouseZone: "REC-01",
    incidentId: "INC-001",
    supervisorId: "david-okonkwo",
    priority: "elevee",
    department: "QA",
  },
  "SCN-003": {
    scnCode: "SCN-003",
    businessUnit: "BU-DIST",
    customerCode: "C-NORD",
    supplierCode: "S-GLAC",
    warehouseZone: "REC / A",
    incidentId: "INC-002",
    supervisorId: "jean-philippe-morin",
    priority: "elevee",
    department: "PROC",
  },
  "SCN-004": {
    scnCode: "SCN-004",
    businessUnit: "BU-DIST",
    customerCode: null,
    supplierCode: "S-STLA",
    warehouseZone: "B-02",
    incidentId: "INC-003",
    supervisorId: "aisha-rahman",
    priority: "elevee",
    department: "INV",
  },
  "SCN-005": {
    scnCode: "SCN-005",
    businessUnit: "BU-DIST",
    customerCode: "C-ARTQ",
    supplierCode: "S-STLA",
    warehouseZone: "REC / B",
    incidentId: "INC-004",
    supervisorId: "marc-andre-tremblay",
    priority: "critique",
    department: "OPS",
  },
  "SCN-006": {
    scnCode: "SCN-006",
    businessUnit: "BU-DIST",
    customerCode: null,
    supplierCode: "S-STLA",
    warehouseZone: "REC-01",
    incidentId: "INC-005",
    supervisorId: "marc-andre-tremblay",
    priority: "normal",
    department: "WH",
  },
  "SCN-007": {
    scnCode: "SCN-007",
    businessUnit: "BU-DIST",
    customerCode: null,
    supplierCode: "S-GLAC",
    warehouseZone: "B-01",
    incidentId: "INC-006",
    supervisorId: "aisha-rahman",
    priority: "elevee",
    department: "WH",
  },
  "SCN-008": {
    scnCode: "SCN-008",
    businessUnit: "BU-FRESH",
    customerCode: "C-LAUR",
    supplierCode: "S-AGRO",
    warehouseZone: "B-zones",
    incidentId: "INC-007",
    supervisorId: "aisha-rahman",
    priority: "elevee",
    department: "WH",
  },
  "SCN-009": {
    scnCode: "SCN-009",
    businessUnit: "BU-IND",
    customerCode: "C-TECH",
    supplierCode: "S-STLA",
    warehouseZone: "A / B",
    incidentId: "INC-008",
    supervisorId: "sophie-lachance",
    priority: "normal",
    department: "INV",
  },
  "SCN-010": {
    scnCode: "SCN-010",
    businessUnit: "BU-IND",
    customerCode: null,
    supplierCode: "S-GLAC",
    warehouseZone: "B-zones",
    incidentId: "INC-009",
    supervisorId: "sophie-lachance",
    priority: "elevee",
    department: "INV",
  },
  "SCN-011": {
    scnCode: "SCN-011",
    businessUnit: "BU-IND",
    customerCode: null,
    supplierCode: "S-STLA",
    warehouseZone: "B-zones",
    incidentId: "INC-010",
    supervisorId: "david-okonkwo",
    priority: "elevee",
    department: "PLAN",
  },
  "SCN-012": {
    scnCode: "SCN-012",
    businessUnit: "All",
    customerCode: "C-PAPI",
    supplierCode: null,
    warehouseZone: "CT-01",
    incidentId: "INC-011",
    supervisorId: "elise-beaumont",
    priority: "critique",
    department: "MGT",
  },
  "SCN-013": {
    scnCode: "SCN-013",
    businessUnit: "BU-DIST",
    customerCode: "C-NORD",
    supplierCode: null,
    warehouseZone: "CT-01",
    incidentId: "INC-012",
    supervisorId: "melanie-gagnon",
    priority: "elevee",
    department: "CS",
  },
  "SCN-014": {
    scnCode: "SCN-014",
    businessUnit: "All",
    customerCode: null,
    supplierCode: null,
    warehouseZone: "CT-01",
    incidentId: "INC-013",
    supervisorId: "elise-beaumont",
    priority: "critique",
    department: "MGT",
  },
  "SCN-015": {
    scnCode: "SCN-015",
    businessUnit: "BU-PEAK",
    customerCode: "C-MTQ",
    supplierCode: "S-PACK",
    warehouseZone: "REC / TRANSIT",
    incidentId: "INC-014",
    supervisorId: "marc-andre-tremblay",
    priority: "pointe",
    department: "OPS",
  },
  "SCN-016": {
    scnCode: "SCN-016",
    businessUnit: "BU-PEAK",
    customerCode: "C-MTQ",
    supplierCode: "S-PACK",
    warehouseZone: "EXP / A",
    incidentId: "INC-015",
    supervisorId: "melanie-gagnon",
    priority: "pointe",
    department: "CS",
  },
  "SCN-017": {
    scnCode: "SCN-017",
    businessUnit: "BU-PEAK",
    customerCode: "C-MTQ",
    supplierCode: "S-GLOB",
    warehouseZone: "CT-01",
    incidentId: "INC-016",
    supervisorId: "elise-beaumont",
    priority: "pointe",
    department: "MGT",
  },
};

export const DEPARTMENT_LABELS: Record<DepartmentCode, { fr: string; en: string }> = {
  WH: { fr: "Entrepôt", en: "Warehouse" },
  REC: { fr: "Réception", en: "Receiving" },
  SHP: { fr: "Expédition", en: "Shipping" },
  INV: { fr: "Inventaire", en: "Inventory" },
  PROC: { fr: "Approvisionnement", en: "Procurement" },
  PLAN: { fr: "Planification", en: "Planning" },
  CS: { fr: "Service client", en: "Customer Service" },
  FIN: { fr: "Finance", en: "Finance" },
  QA: { fr: "Qualité", en: "Quality" },
  OPS: { fr: "Opérations", en: "Operations" },
  MGT: { fr: "Direction", en: "Management" },
};

export const PRIORITY_LABELS: Record<PriorityLevel, { fr: string; en: string }> = {
  normal: { fr: "Normal", en: "Normal" },
  elevee: { fr: "Élevée", en: "High" },
  critique: { fr: "Critique", en: "Critical" },
  pointe: { fr: "Pointe", en: "Peak" },
};

export const CAREER_CHAPTER_LABELS: Record<number, { fr: string; en: string }> = {
  1: { fr: "Chapitre 1 — Intégration chez Concorde Logistics", en: "Chapter 1 — Onboarding at Concorde Logistics" },
  2: { fr: "Chapitre 2 — Stratégie de stockage et exécution au sol", en: "Chapter 2 — Storage strategy and floor execution" },
  3: { fr: "Chapitre 3 — Gouvernance des stocks et réponse à la demande", en: "Chapter 3 — Stock governance and demand response" },
  4: { fr: "Chapitre 4 — Tour de contrôle et amélioration continue", en: "Chapter 4 — Control tower and continuous improvement" },
  5: { fr: "Chapitre 5 — Leadership de crise — Semaine de pointe", en: "Chapter 5 — Crisis leadership — Peak Week" },
};

export function getScenarioBinding(scnCode: string): ScenarioUniverseBinding | undefined {
  return SCENARIO_UNIVERSE_BINDINGS[scnCode];
}
