import type { MissionData } from "./missionData";

/** Static display content for SCN-006 to SCN-017 (M2–M5). No scenario logic. */
export const EXTENDED_MISSIONS: Record<string, MissionData> = {
  "SCN-006": {
    scenarioId: 6,
    scnCode: "SCN-006",
    objective: "Exécuter un rangement structuré depuis le quai vers un emplacement STOCKAGE conforme aux règles de capacité.",
    context:
      "PO-M2-001 · GR-M2-001 postées : 150 u. SKU-001 · lot LOT-2025-001 au quai REC-01. Contrat putaway : REC-01 → B-01-R1-L1 · lot LOT-2025-001 obligatoire.",
    role: "Spécialiste Rangement (Putaway Specialist)",
    module: "WM — Exécution d'entrepôt",
    controlPoints: [
      "Documents : PO-M2-001 · GR-M2-001 (POSTED) · SKU-001 · 150 u. · REC-01.",
      "Lot contractuel : LOT-2025-001 — obligatoire au PUTAWAY M2.",
      "Destination contractuelle : B-01-R1-L1 (zone STOCKAGE).",
      "Valider la précision stock avant conformité avancée.",
    ],
    studentActions: [
      "Confirmer PO-M2-001 et GR-M2-001 POSTED · 150 u. SKU-001 · REC-01.",
      "PUTAWAY (LT01) : REC-01 → B-01-R1-L1 · 150 u. · lot LOT-2025-001.",
      "FIFO_PICK selon les étapes du flux M2.",
      "STOCK_ACCURACY puis COMPLIANCE_ADV.",
    ],
    expectedOutcome: "Marchandise rangée en B-01-R1-L1 avec lot LOT-2025-001, conformité M2 validée.",
    supervisorNotes:
      "Lot LOT-2025-001 est contractuel — saisir ce numéro exact au PUTAWAY. Flux M2 : GR → PUTAWAY → FIFO_PICK → STOCK_ACCURACY → COMPLIANCE_ADV.",
    technicalSpecs: {
      sku: "SKU-001",
      quantity: 150,
      sourceBin: "REC-01",
      targetBin: "B-01-R1-L1",
      lotNumber: "LOT-2025-001",
      poRef: "PO-M2-001",
      grRef: "GR-M2-001",
      expectedTransaction: "PUTAWAY (LT01) — REC-01 → B-01-R1-L1 · LOT-2025-001",
      status: "GR postée — stock au quai",
      warehouse: "CDC Montréal",
    },
    successCriteria: ["Putaway vers bin STOCKAGE valide", "Séquence M2 respectée", "Score ≥ 60 en évaluation"],
    failureConditions: ["Putaway sans GR postée", "Bin hors zone STOCKAGE", "Séquence hors ordre"],
    wmsFunction: "Putaway / slotting",
    sapEquivalent: "LT01, LT12, WM-TO",
    odooEquivalent: "Internal Transfers, Putaway rules",
    industryRelevance: "Slotting et traçabilité emplacement en entrepôt automatisé.",
    demoGuidance: "Explorez les capacités bin sans pénalité officielle.",
    evalGuidance: "Chaque erreur de zone ou séquence est pénalisée et compte pour la certification M2.",
    recoveryPaths: ["Choisir un bin alternatif si capacité dépassée"],
    alternativeActions: ["Ranger en zone non-STOCKAGE sans vérifier les règles d'emplacement"],
    wrongActionConsequences: ["Putaway hors zone → pénalité OUT_OF_SEQUENCE"],
  },
  "SCN-007": {
    scenarioId: 7,
    scnCode: "SCN-007",
    objective:
      "Respecter la capacité maximale des emplacements et répartir une réception de 600 unités sur deux bins (500 + 100).",
    context:
      "PO-M2-002 et GR-M2-002 sont déjà enregistrés. Une quantité de 600 unités de SKU-002, lot LOT-2025-002, est disponible dans l'emplacement REC-01. L'emplacement B-01-R1-L1 possède une capacité maximale de 500 unités. Vous devez effectuer deux opérations de rangement en conservant le même numéro de lot : 500 unités vers B-01-R1-L1, puis 100 unités restantes vers B-01-R1-L2. Une fois les 600 unités entièrement rangées, contrôlez la précision du stock et terminez la vérification de conformité.",
    role: "Planificateur Capacité (Capacity Planner)",
    module: "WM — Gestion des emplacements",
    controlPoints: [
      "Documents : PO-M2-002 · GR-M2-002 · SKU-002 · LOT-2025-002 · 600 u. · REC-01.",
      "Premier PUTAWAY : LOT-2025-002 · 500 u. · REC-01 → B-01-R1-L1.",
      "Deuxième PUTAWAY : LOT-2025-002 · 100 u. · REC-01 → B-01-R1-L2.",
      "Condition de passage : REC-01 = 0 · total stock = 600.",
      "Ensuite : STOCK_ACCURACY · COMPLIANCE_ADV.",
    ],
    studentActions: [
      "Confirmer GR-M2-002 POSTED · 600 u. SKU-002 · LOT-2025-002 · REC-01.",
      "PUTAWAY 1 : 500 u. · LOT-2025-002 · REC-01 → B-01-R1-L1.",
      "PUTAWAY 2 : 100 u. · LOT-2025-002 · REC-01 → B-01-R1-L2 (REC-01 = 0).",
      "STOCK_ACCURACY : vérifier total 600 · L1=500 · L2=100.",
      "COMPLIANCE_ADV.",
    ],
    expectedOutcome:
      "600 u. réparties 500+100 sans overflow, lot LOT-2025-002 conservé, REC-01 vide, total 600, conformité M2.",
    supervisorNotes:
      "Apprentissage unique : capacité d'emplacement. Split obligatoire 500+100 du lot LOT-2025-002. Pas de FIFO dans ce scénario — le FIFO est enseigné en SCN-008.",
    technicalSpecs: {
      sku: "SKU-002",
      quantity: 600,
      sourceBin: "REC-01",
      targetBin: "B-01-R1-L1 (500 u.) + B-01-R1-L2 (100 u.)",
      lotNumber: "LOT-2025-002",
      poRef: "PO-M2-002",
      grRef: "GR-M2-002",
      expectedTransaction: "PUTAWAY split 500+100 — LOT-2025-002 · puis STOCK_ACCURACY · COMPLIANCE_ADV",
      status: "GR postée — capacité uniquement (pas de FIFO)",
      warehouse: "CDC Montréal",
    },
    successCriteria: [
      "Deux PUTAWAY : 500 + 100 du lot LOT-2025-002",
      "REC-01 à 0 après le split",
      "Aucun bin au-delà de sa capacité",
      "Total stock = 600",
      "Traçabilité lot conservée",
    ],
    failureConditions: [
      "Single-bin overflow (600 dans B-01-R1-L1)",
      "PUTAWAY partiel (ex. 400) accepté / posté",
      "Lot incorrect",
      "Saldo residual em REC-01",
    ],
    wmsFunction: "Bin capacity control",
    sapEquivalent: "LS01, capacity checks in WM",
    odooEquivalent: "Storage capacity, location constraints",
    industryRelevance: "Éviter saturation des emplacements lors d'une réception volumineuse.",
    demoGuidance:
      "Tentez 600 dans B-01-R1-L1 pour voir l'alerte capacité, puis répartissez 500 + 100.",
    evalGuidance:
      "La répartition exacte 500+100 est obligatoire. Un solde en REC-01 bloque la progression. Aucun FIFO dans ce scénario.",
    recoveryPaths: ["Utiliser B-01-R1-L2 pour les 100 u. restantes"],
    alternativeActions: [
      "Forcer les 600 unités dans un seul bin malgré l'alerte capacité",
      "Ranger seulement 400 u. et passer à la suite",
    ],
    wrongActionConsequences: [
      "Capacité dépassée → erreur opérationnelle et pénalité",
      "Split incomplet → PUTAWAY non validé, non-conformité",
    ],
  },
  "SCN-008": {
    scenarioId: 8,
    scnCode: "SCN-008",
    objective: "Appliquer FIFO sur trois lots du même SKU lors du prélèvement (rangement déjà effectué).",
    context:
      "Trois lots SKU-003 sont préchargés en zone STOCKAGE (rangement déjà posté) : LOT-A (jan, B-01-R1-L1), LOT-B (fév, B-01-R1-L2), LOT-C (mars, B-02-R1-L1). Aucun PUTAWAY requis — observez les dates de réception dans le cockpit, validez l'ordre FIFO, puis prélevez le lot le plus ancien (FIFO_PICK).",
    role: "Spécialiste FIFO",
    module: "WM — Traçabilité lots",
    controlPoints: [
      "Comparer les dates de réception des trois lots dans le cockpit.",
      "Confirmer que LOT-A est le lot le plus ancien.",
      "Prélever LOT-A avant LOT-B et LOT-C lors du FIFO_PICK.",
      "Ne pas mélanger les lots dans un même mouvement.",
    ],
    studentActions: [
      "Observer le stock préchargé : 3 lots SKU-003 déjà rangés sur B-01-R1-L1, B-01-R1-L2, B-02-R1-L1.",
      "Valider l'ordre FIFO : LOT-A (jan) → LOT-B (fév) → LOT-C (mars).",
      "Exécuter FIFO_PICK sur le lot le plus ancien (PUTAWAY déjà complété au démarrage).",
      "Compléter STOCK_ACCURACY et COMPLIANCE_ADV.",
    ],
    expectedOutcome: "Prélèvement conforme FIFO, traçabilité lot intacte.",
    supervisorNotes: "LOT-A (jan) doit sortir avant LOT-B et LOT-C. Violation FIFO = échec conformité.",
    technicalSpecs: {
      sku: "SKU-003",
      quantity: 300,
      sourceBin: "B-01-R1-L1 / B-01-R1-L2 / B-02-R1-L1",
      targetBin: "Zone EXPÉDITION (FIFO_PICK)",
      expectedTransaction: "FIFO_PICK — LOT-A en premier",
      status: "3 lots préchargés en STOCKAGE — putaway auto ; démarrage à FIFO_PICK",
    },
    successCriteria: ["Lot oldest picked first", "Traçabilité lot conservée"],
    failureConditions: ["Pick lot récent avant ancien", "Mélange lots non autorisé"],
    wmsFunction: "FIFO / FEFO picking",
    sapEquivalent: "FIFO strategy, batch determination",
    odooEquivalent: "Removal strategy FIFO, lots",
    industryRelevance: "Conformité alimentaire/pharma et réduction obsolescence.",
    demoGuidance: "Comparez dates de réception des lots dans le cockpit.",
    evalGuidance: "Mauvais lot = pénalité FIFO et échec conformité.",
    recoveryPaths: ["Re-pick avec lot correct si erreur en démo"],
    alternativeActions: [
      "Prélever LOT-C avant LOT-A — violation FIFO client",
      "Mélanger deux lots dans un même mouvement",
    ],
    wrongActionConsequences: ["Violation FIFO → pénalité et client non servi correctement"],
  },
  "SCN-009": {
    scenarioId: 9,
    scnCode: "SCN-009",
    objective: "Réaliser un inventaire cyclique simple et identifier les écarts système/physique.",
    context:
      "Stock système préchargé : SKU-001 = 100 u. (B-01-R1-L1), SKU-003 = 80 u. (B-01-R1-L2). Le comptage physique révélera un écart de −3 sur SKU-001. Observez les quantités système, saisissez les quantités physiques réelles, puis réconciliez.",
    role: "Auditeur Inventaire (Inventory Auditor)",
    module: "IM — Inventaire cyclique",
    controlPoints: [
      "Générer la liste de comptage (CC_LIST) complète.",
      "Saisir les quantités physiques exactes au CC_COUNT.",
      "Identifier l'écart −3 sur SKU-001 à la réconciliation.",
      "CC_RECON : poster l'ajustement ADJ (MI07) pour l'écart −3 sur SKU-001.",
    ],
    studentActions: [
      "CC_LIST : identifier SKU-001 et SKU-003 à compter.",
      "CC_COUNT : saisir quantités physiques (SKU-001 ≠ 100, SKU-003 = 80).",
      "CC_RECON : analyser l'écart −3, puis poster l'ajustement ADJ (MI07) sur SKU-001.",
      "REPLENISH : non requis (auto-validé) — passer à COMPLIANCE_M3.",
    ],
    expectedOutcome: "Écart −3 identifié et réconcilié, conformité M3 validée.",
    supervisorNotes: "L'écart −3 sur SKU-001 est intentionnel — ne pas ignorer à la réconciliation.",
    technicalSpecs: {
      sku: "SKU-001 / SKU-003",
      quantity: "100 / 80 (système)",
      sourceBin: "B-01-R1-L1 / B-01-R1-L2",
      targetBin: "N/A — comptage sur place",
      expectedTransaction: "CC_COUNT → CC_RECON + ADJ (MI07) — écart −3",
      status: "Écart −3 attendu sur SKU-001",
    },
    successCriteria: ["Écart détecté", "Réconciliation documentée", "Score ≥ 70"],
    failureConditions: ["Ignorer écart", "Ajuster sans justification"],
    wmsFunction: "Cycle counting",
    sapEquivalent: "MI01, MI04, MI07",
    odooEquivalent: "Inventory adjustments, cycle counts",
    industryRelevance: "Inventaire perpétuel vs arrêt annuel.",
    demoGuidance: "Pratiquez la saisie MI01 sans impact certification.",
    evalGuidance: "Justification requise pour tout ajustement significatif.",
    recoveryPaths: ["Re-saisir quantité physique correcte", "CC_RECON : saisir variance −3 et valider MI07 avant clôture."],
    wrongActionConsequences: ["Écart non résolu bloque COMPLIANCE_M3"],
  },
  "SCN-010": {
    scenarioId: 10,
    scnCode: "SCN-010",
    objective: "Analyser un écart significatif (−28) et produire un ajustement justifié.",
    context:
      "SKU-006 : stock système 380 u. (B-02-R1-L1) après expédition partielle. Le comptage physique révèle 352 u. — écart de −28, au-delà du seuil d'ajustement (20 u.). Observez l'écart, justifiez la cause, puis ajustez.",
    role: "Gestionnaire Inventaire",
    module: "IM — Variance management",
    controlPoints: [
      "Confirmer stock système 380 u. avant comptage.",
      "Saisir quantité physique réelle (352 u.) au CC_COUNT.",
      "Documenter l'écart −28 (> seuil 20) à CC_RECON.",
      "Poster l'ajustement ADJ avec justification.",
    ],
    studentActions: [
      "CC_LIST : cibler SKU-006 / B-02-R1-L1.",
      "CC_COUNT : saisir 352 u. (physique) vs 380 u. (système).",
      "CC_RECON : justifier l'écart −28 (seuil dépassé).",
      "REPLENISH si requis, puis COMPLIANCE_M3.",
    ],
    expectedOutcome: "Variance −28 justifiée et ajustée, conformité verte.",
    supervisorNotes: "Ne pas ajuster sans analyse — seuil interne = 20 unités.",
    technicalSpecs: {
      sku: "SKU-006",
      quantity: 380,
      sourceBin: "B-02-R1-L1",
      targetBin: "N/A — ajustement sur place",
      expectedTransaction: "CC_RECON + ADJ (MI07) — écart −28",
      status: "Variance significative — justification requise",
    },
    successCriteria: ["Justification fournie", "ADJ posté", "Conformité verte"],
    failureConditions: ["ADJ sans justification", "Ignorer écart > seuil"],
    wmsFunction: "Variance analysis & adjustment",
    sapEquivalent: "MI07, difference analysis",
    odooEquivalent: "Inventory valuation adjustment",
    industryRelevance: "Réconciliation mensuelle comptabilité/stocks.",
    demoGuidance: "Testez différentes justifications en mode démo.",
    evalGuidance: "Justification obligatoire pour SCN-010 en évaluation.",
    recoveryPaths: ["Documenter cause racine puis ADJ"],
    alternativeActions: [
      "Ajuster l'écart −28 sans justification écrite",
      "Passer COMPLIANCE_M3 sans résoudre l'écart documenté",
    ],
    wrongActionConsequences: ["Ajustement non conforme → audit trail incomplet"],
  },
  "SCN-011": {
    scenarioId: 11,
    scnCode: "SCN-011",
    objective: "Générer des recommandations de réapprovisionnement selon Min/Max et stock de sécurité.",
    context:
      "Niveaux actuels : SKU-004 = 30 u. (Min 50, Max 200, SS 25) et SKU-005 = 40 u. (Min 80, Max 300, SS 30). Les deux SKU sont sous le seuil Min. Analysez les paramètres, calculez le besoin, puis générez les recommandations REPLENISH.",
    role: "Planificateur Approvisionnement (Supply Planner)",
    module: "MRP / Replenishment",
    controlPoints: [
      "Détecter SKU-004 et SKU-005 sous seuil Min.",
      "Consulter paramètres Min/Max/SS et lead time.",
      "Calculer quantités de réapprovisionnement (Min–Max : Q = Max − stock actuel).",
      "Valider REPLENISH avec quantités cohérentes.",
    ],
    studentActions: [
      "REPLENISH : identifier SKU-004 (30) et SKU-005 (40) sous Min.",
      "Comparer aux seuils Min (50 / 80), Max (200 / 300) et SS (25 / 30) comme indicateur de risque.",
      "Calculer Q = Max − stock actuel pour chaque SKU (170 / 260) et soumettre une recommandation.",
      "COMPLIANCE_M3 une fois les deux recommandations validées.",
    ],
    expectedOutcome: "Suggestions de réappro conformes Min/Max, conformité M3.",
    supervisorNotes: "SKU-004 et SKU-005 nécessitent réappro — ne pas sous-estimer le besoin.",
    technicalSpecs: {
      sku: "SKU-004 / SKU-005",
      quantity: "30 / 40 (sous Min)",
      sourceBin: "B-01-R1-L1 / B-01-R1-L2",
      targetBin: "N/A — recommandation achat",
      expectedTransaction: "REPLENISH — Min-Max (Q = Max − stock)",
      status: "Sous seuil Min — réappro requis",
    },
    successCriteria: ["Seuils Min/Max respectés", "Quantités recommandées cohérentes"],
    failureConditions: ["Sous-réapprovisionnement", "Ignorer stock de sécurité"],
    wmsFunction: "Replenishment planning",
    sapEquivalent: "MD04, reorder point",
    odooEquivalent: "Reordering rules, Min/Max",
    industryRelevance: "Éviter ruptures tout en limitant stock dormant.",
    demoGuidance: "Comparez formules Min/Max dans le panneau learning.",
    evalGuidance: "Calcul Min/Max évalué : Q = Stock max − Stock actuel pour chaque SKU.",
    recoveryPaths: ["Recalculer besoin net puis REPLENISH"],
    alternativeActions: [
      "Réapprovisionner en quantité inférieure au besoin calculé",
      "Ignorer le stock de sécurité dans le calcul ROP",
    ],
    wrongActionConsequences: ["Rupture client si réappro insuffisant"],
  },
  "SCN-012": {
    scenarioId: 12,
    scnCode: "SCN-012",
    objective: "Recommander une politique stock au comité finance — les 48 000 $ immobilisés sont-ils justifiés ?",
    context:
      "Revue Q3 du CFO sur le working capital. Données KPI préchargées : rotation 6× (bande normale 4–12). Votre rôle : classifier la bande et recommander maintien, réduction ciblée ou hausse — pas une chasse au surstock. Module analytique — aucune transaction physique.",
    role: "Analyste Logistique — revue capital circulant",
    module: "CO-PA / Logistics controlling",
    controlPoints: [
      "Consulter KPI_DATA avant interprétation.",
      "Classifier la rotation dans la bande normale (6×).",
      "Recommander politique stock (maintien / réduction SKU / hausse).",
      "Éviter complaisance sans surveillance SKU.",
    ],
    studentActions: [
      "KPI_DATA : consulter le tour de contrôle KPI.",
      "KPI_ROTATION : classifier 6× et recommander au comité finance.",
      "KPI_SERVICE puis KPI_DIAGNOSTIC : synthèse politique stock.",
      "COMPLIANCE_M4 une fois diagnostic validé.",
    ],
    expectedOutcome: "Politique stock recommandée avec surveillance SKU — pas de destock global injustifié.",
    supervisorNotes: "M4 analytique — rotation normale @ 6×. Seuil 70/100. COMPLIANCE_M4 valide les interprétations, pas l'inventaire M1.",
    technicalSpecs: {
      sku: "N/A — analyse portefeuille",
      quantity: "KPI-driven",
      sourceBin: "N/A",
      targetBin: "N/A",
      expectedTransaction: "KPI_DATA → KPI_ROTATION → KPI_DIAGNOSTIC",
      status: "Rotation 6× — bande normale — revue politique stock",
    },
    successCriteria: ["Bande normale identifiée", "Politique stock avec surveillance SKU"],
    failureConditions: ["Surstock déclaré à 6×", "Complaisance sans action"],
    wmsFunction: "KPI analytics",
    sapEquivalent: "MC$4, Inventory turnover reports",
    odooEquivalent: "Inventory reports, stock valuation",
    industryRelevance: "Optimisation working capital sans sur-réaction.",
    demoGuidance: "Explorez les formules KPI en démo.",
    evalGuidance: "Seuil 70/100 — COMPLIANCE_M4 valide cohérence interprétation/decision.",
    recoveryPaths: ["Reformuler avec maintien + surveillance SKU"],
    alternativeActions: [
      "Déclarer surstock sans appliquer la bande 4–12×",
      "Conclure « rien à faire » sans plan de surveillance",
    ],
    wrongActionConsequences: [
      "Misclassification surstock → destock coûteux inutile",
      "Complaisance sans monitoring SKU → dérive capital non détectée",
    ],
  },
  "SCN-013": {
    scenarioId: 13,
    scnCode: "SCN-013",
    objective: "Arbitrer le budget formation J-90 avant renouvellement SLA — tableau vert ou piège OTIF ?",
    context:
      "Renouvellement contrat grand compte dans 90 jours. Dashboard vert : service 95 % (excellent au seuil) et erreurs 4 % (acceptable). Votre mission : reconnaître l'excellence affichée, corréler erreurs picking/réception au risque OTIF, et proposer un plan d'exécution chiffré — pas diagnostiquer un « faible service ».",
    role: "Responsable Performance — revue SLA J-90",
    module: "Logistics Performance Management",
    controlPoints: [
      "Reconnaître service excellent @ 95 %.",
      "Corréler erreurs 4 % au risque OTIF (picking, réception).",
      "Proposer plan mesurable (% cible, horizon 90 jours).",
      "Ne pas proposer destock comme levier principal.",
    ],
    studentActions: [
      "KPI_DATA : charger indicateurs service et erreurs.",
      "KPI_ROTATION : contexte portefeuille si requis.",
      "KPI_SERVICE : analyser OTIF et taux d'erreur.",
      "KPI_DIAGNOSTIC → COMPLIANCE_M4.",
    ],
    expectedOutcome: "Plan exécution picking/réception avec cible chiffrée et suivi hebdomadaire.",
    supervisorNotes: "Piège tableau vert — erreurs corrigeables menacent OTIF malgré 95 % service.",
    technicalSpecs: {
      sku: "N/A — indicateurs agrégés",
      quantity: "KPI service + erreurs",
      sourceBin: "N/A",
      targetBin: "N/A",
      expectedTransaction: "KPI_SERVICE → KPI_DIAGNOSTIC",
      status: "Service excellent au seuil — exécution amber (erreurs 4 %)",
    },
    successCriteria: ["Excellence reconnue", "Corrélation erreurs/OTIF", "Plan chiffré 90 jours"],
    failureConditions: ["Diagnostic service-only sans erreurs", "Destock comme levier principal"],
    wmsFunction: "Service level monitoring",
    sapEquivalent: "OTIF, VL06O performance",
    odooEquivalent: "Delivery performance, SLA dashboards",
    industryRelevance: "OTIF contractuel grands comptes — fragilité au seuil.",
    demoGuidance: "Testez scénarios what-if en démo.",
    evalGuidance: "Évaluation sur qualité diagnostic + corrélation erreurs.",
    recoveryPaths: ["Réanalyser corrélation erreurs picking/réception/OTIF"],
    alternativeActions: [
      "Diagnostiquer un faible service alors que 95 % est excellent",
      "Proposer destock sans cadrage qualité d'exécution",
    ],
    wrongActionConsequences: ["Mauvais levier → SLA non renouvelé", "OTIF dégradé malgré dashboard vert"],
  },
  "SCN-014": {
    scenarioId: 14,
    scnCode: "SCN-014",
    objective: "Arbitrer une initiative unique au S&OP mensuel — CFO, Ventes et Ops en conflit.",
    context:
      "Réunion S&OP mensuelle : CFO (capital), Ventes (OTIF), Ops (exécution) — budget limité à une initiative financée. Capstone M4 : rotation 6× normale, service 95 % excellent, erreurs 4 % acceptables, délai 3,5 j. Formulez un paragraphe décisionnel board-ready avec trade-offs explicites et KPI de suivi sur 90 jours.",
    role: "Directeur des Opérations — arbitrage S&OP",
    module: "Strategic Logistics Control Tower",
    controlPoints: [
      "Citer ≥ 3 domaines KPI (rotation, service, erreurs, délai).",
      "Nommer un levier prioritaire et ce qui est reporté.",
      "Articuler trade-offs (maintien service vs capital vs exécution).",
      "Définir cibles de suivi sur 90 jours.",
    ],
    studentActions: [
      "Pipeline KPI complet : DATA → ROTATION → SERVICE.",
      "KPI_DIAGNOSTIC : paragraphe board avec arbitrage et trade-offs.",
      "COMPLIANCE_M4 une fois décision argumentée.",
    ],
    expectedOutcome: "Décision intégrée : levier, sacrifice, KPIs de suivi — une initiative financée.",
    supervisorNotes: "Capstone M4 — niveau Evaluate. Seuil 70/100. Intégration 012 (capital) + 013 (exécution).",
    technicalSpecs: {
      sku: "N/A — multi-KPI",
      quantity: "Rotation + service + erreurs + lead time 3,5 j",
      sourceBin: "N/A",
      targetBin: "N/A",
      expectedTransaction: "KPI_DIAGNOSTIC stratégique → COMPLIANCE_M4",
      status: "S&OP — arbitrage multi-indicateurs requis",
    },
    successCriteria: ["Synthèse multi-indicateurs", "Décision argumentée"],
    failureConditions: ["Analyse mono-KPI", "Décision sans justification"],
    wmsFunction: "Integrated performance diagnosis",
    sapEquivalent: "Embedded analytics, SAC",
    odooEquivalent: "Spreadsheet / BI dashboards",
    industryRelevance: "S&OP et revue performance mensuelle.",
    demoGuidance: "Comparez plusieurs options stratégiques en démo.",
    evalGuidance: "Seuil 70/100 — qualité décision évaluée.",
    recoveryPaths: ["Revoir trade-offs stock/service/coût"],
    alternativeActions: [
      "Décision basée sur un seul KPI — ignore les trade-offs",
      "Recommandation sans justification liée aux KPI combinés",
    ],
    wrongActionConsequences: ["Décision sous-optimale → perte compétitivité"],
  },
  "SCN-015": {
    scenarioId: 15,
    scnCode: "SCN-015",
    objective: "Protéger une commande prioritaire sans désorganiser le flux",
    context:
      "Quart de clôture Peak Week — mission 1/3. Rôle : Superviseur d'exploitation. " +
      "Contrat : stock initial 0 · inbound 50 u. SKU-001 · PO-M5-001 · LOT-M5-A · REC-01 → B-01-R1-L1 · capacité 100 · Min 10 / Max 100 / SS 5. " +
      "Priorité client CLI-PRIORITAIRE-A : protéger ≥10 u. disponibles sans ajustement artificiel. Q = 0 si stock ≥ minimum.",
    role: "Superviseur d'exploitation — quart de clôture",
    module: "M5 — EXÉCUTER → MESURER → RÉCONCILIER → ARBITRER → DÉFENDRE",
    controlPoints: [
      "Priorité CLI-PRIORITAIRE-A · réserve minimale 10 u. (contrainte de décision, pas un pick/GI).",
      "M5_RECEPTION : SKU-001 · 50 u. · PO-M5-001 · REC-01.",
      "M5_PUTAWAY : REC-01 → B-01-R1-L1 · lot LOT-M5-A · capacité 100.",
      "Comptage nominal (pas d'écart) → aucun ajustement artificiel.",
      "M5_REPLENISH : Min 10 · Max 100 — Q = 0 attendu si stock ≥ 10.",
      "Clôturer avec preuves de session réelles (parcours, stock final, Q, conformité).",
    ],
    studentActions: [
      "Réceptionner 50 u. (PO-M5-001) puis ranger vers B-01-R1-L1 (LOT-M5-A).",
      "Vérifier le cycle sans inventer d'écart — ne pas forcer un ajustement.",
      "Calculer Q : stock final vs minimum 10 → accepter Q = 0 si correct.",
      "Décision tactique : protéger la priorité client via le minimum, sans désorganiser le flux.",
      "Message : « Une opération conforme ne nécessite pas une correction artificielle. »",
    ],
    expectedOutcome:
      "Cycle nominal conforme · priorité protégée (stock ≥ 10) · Q = 0 · aucune correction artificielle · preuves de session disponibles pour le bilan.",
    supervisorNotes:
      "Mission cumulative 1/3. La priorité se valide par le respect du minimum et l'absence d'ajustement inutile — pas par un picking inventé. Préparer les preuves pour SCN-016 puis SCN-017.",
    technicalSpecs: {
      sku: "SKU-001",
      quantity: 50,
      sourceBin: "REC-01",
      targetBin: "B-01-R1-L1",
      lotNumber: "LOT-M5-A",
      poRef: "PO-M5-001",
      replenishMin: 10,
      replenishMax: 100,
      replenishSafetyStock: 5,
      expectedTransaction: "M5_RECEPTION → M5_PUTAWAY → M5_CYCLE_COUNT → M5_REPLENISH → M5_KPI → M5_DECISION",
      status: "Peak Week — mission 1/3 · priorité CLI-PRIORITAIRE-A · Q=0 attendu",
      warehouse: "CDC Montréal",
    },
    successCriteria: [
      "Réception + putaway conformes",
      "Aucun ajustement artificiel",
      "Q = 0 si stock ≥ min 10",
      "Score ≥ 70",
    ],
    failureConditions: ["Ajustement sans écart", "Q positif injustifié", "Minimum non respecté dans le raisonnement"],
    wmsFunction: "Integrated inbound + stock decision",
    sapEquivalent: "EWM GR / putaway / replenishment decision",
    odooEquivalent: "Receipt / internal transfer / replenishment rule",
    industryRelevance: "Clôture de quart sous contrainte de service prioritaire.",
    demoGuidance: "Parcourez le cycle nominal et validez Q = 0 sans inventer de problème.",
    evalGuidance:
      "Décision tactique basée sur preuves de session. Message attendu : opération conforme ⇒ pas de correction artificielle.",
    recoveryPaths: ["Reprendre le cycle ops si une étape manque"],
    alternativeActions: [
      "Forcer un ajustement sans écart",
      "Commander un réappro alors que stock ≥ minimum",
    ],
    wrongActionConsequences: ["Correction artificielle → preuves de session faussées pour le bilan"],
  },
  "SCN-016": {
    scenarioId: 16,
    scnCode: "SCN-016",
    objective: "Réconcilier avant de décider",
    context:
      "Quart de clôture — mission 2/3 (suite de SCN-015). Même contrat ops + variance injectée : système 50 · physique 45 · écart −5. " +
      "Décision de stock bloquée tant que l'écart n'est pas réconcilié. Après ajustement −5 : stock corrigé 45 · min 10 · Q = 0. " +
      "Message : « Réconcilier d'abord, décider ensuite. »",
    role: "Superviseur d'exploitation — quart de clôture",
    module: "M5 — EXÉCUTER → MESURER → RÉCONCILIER → ARBITRER → DÉFENDRE",
    controlPoints: [
      "Continuité mission : priorité CLI-PRIORITAIRE-A toujours active (min 10).",
      "Variance contractuelle : système 50 · physique 45 · −5 @ B-01-R1-L1.",
      "M5_ADJ obligatoire avant réappro / KPI / décision.",
      "Après correction : stock corrigé 45 · exactitude 90 % → 100 % · Q = 0.",
      "Ajustement ≠ réapprovisionnement.",
    ],
    studentActions: [
      "Compléter réception + putaway (même contrat que SCN-015).",
      "Comptage : saisir 45 (système 50) — constater −5.",
      "Poster l'ajustement −5, puis seulement décider Q.",
      "Vérifier Q = 0 (45 ≥ min 10) et clôturer avec preuves de réconciliation.",
    ],
    expectedOutcome:
      "Écart −5 réconcilié · stock corrigé 45 · Q = 0 · leçon « réconcilier d'abord, décider ensuite » démontrée.",
    supervisorNotes:
      "Mission cumulative 2/3. Bloquer toute décision de stock tant que l'écart est ouvert. Les preuves (variance, exactitude, stock corrigé, Q) alimentent SCN-017.",
    technicalSpecs: {
      sku: "SKU-001",
      quantity: "Système 50 u. · Physique 45 u. · Variance −5",
      sourceBin: "REC-01",
      targetBin: "B-01-R1-L1",
      lotNumber: "LOT-M5-A",
      poRef: "PO-M5-001",
      replenishMin: 10,
      replenishMax: 100,
      replenishSafetyStock: 5,
      expectedTransaction: "M5_CYCLE_COUNT → M5_ADJ → M5_REPLENISH → M5_KPI",
      status: "Peak Week — mission 2/3 · variance −5 · ADJ requis",
      warehouse: "CDC Montréal",
    },
    successCriteria: ["Variance résolue", "Stock corrigé 45", "Q = 0", "Décision post-réconciliation"],
    failureConditions: ["Compliance avec écart ouvert", "ADJ manquant", "Décider Q avant réconciliation"],
    wmsFunction: "Exception management",
    sapEquivalent: "MI07 in integrated flow",
    odooEquivalent: "Inventory adjustment wizard",
    industryRelevance: "Gestion d'écart en clôture de quart.",
    demoGuidance: "Rejouez CC → ADJ → Q = 0 en démo.",
    evalGuidance: "Correction obligatoire avant KPI/décision. Distinguer ajustement et réappro.",
    recoveryPaths: ["CC → ADJ → reprise flux"],
    alternativeActions: [
      "Passer à M5_KPI sans corriger l'écart",
      "Commander un réappro pour « corriger » l'écart",
    ],
    wrongActionConsequences: ["Stock incorrect → décision de stock erronée"],
  },
  "SCN-017": {
    scenarioId: 17,
    scnCode: "SCN-017",
    objective: "Présenter le bilan du quart et défendre le prochain plan d'action",
    context:
      "Quart de clôture — mission 3/3 (bilan). Continuité pédagogique scellée : " +
      "(1) SCN-015 — cycle nominal, priorité protégée, Q = 0, pas de correction artificielle ; " +
      "(2) SCN-016 — variance −5 réconciliée, exactitude 90 %→100 %, stock corrigé 45, Q = 0. " +
      "Défendez avec ≥3 preuves de VOTRE session courante (parcours, variance, exactitude, stock corrigé/final, Q, conformité, issues). " +
      "Interdit : portfolio M4 6×/95 %/4 %/3,5 j/48 000 $, OTIF inventé, backlog inventé.",
    role: "Superviseur d'exploitation — quart de clôture",
    module: "M5 — EXÉCUTER → MESURER → RÉCONCILIER → ARBITRER → DÉFENDRE",
    controlPoints: [
      "Structure obligatoire : preuves (≥3) → diagnostic → priorité → compromis → horizon → recommandation.",
      "Continuité scellée SCN-015 : réception 50 + putaway · priorité CLI-PRIORITAIRE-A · Q = 0 · pas de correction artificielle.",
      "Continuité scellée SCN-016 : système 50 · physique 45 · variance −5 · ADJ −5 · stock corrigé 45 · exactitude 90 %→100 % · Q = 0.",
      "Preuves autorisées (session courante) : parcours, variance, exactitude avant/après, stock corrigé/final, Q, conformité, issues, temps de session.",
      "Ne pas citer 6× / 95 % / 4 % / 3,5 j / 48 000 $ / OTIF inventé / backlog inventé.",
      "Compléter le cycle ops de cette session avant la défense — la note repose sur vos preuves live.",
    ],
    studentActions: [
      "Exécuter le cycle ops de la session (preuves live).",
      "Lire le moniteur de preuves de session (pas le portfolio M4).",
      "Rédiger le bilan : 6 dimensions + ≥3 preuves chiffrées/concepts de session.",
      "Proposer le plan du prochain quart avec horizon explicite.",
    ],
    expectedOutcome:
      "Bilan du quart défendu avec preuves de session · portes stratégiques validées · conformité Gold-path.",
    supervisorNotes:
      "Mission cumulative 3/3. Les résumés SCN-015/016 du briefing sont scellés pédagogiquement ; la note repose sur les preuves de la session courante. Pas d'OTIF/backlog inventés.",
    technicalSpecs: {
      sku: "SKU-001",
      quantity: 50,
      sourceBin: "REC-01",
      targetBin: "B-01-R1-L1",
      lotNumber: "LOT-M5-A",
      poRef: "PO-M5-001",
      replenishMin: 10,
      replenishMax: 100,
      replenishSafetyStock: 5,
      expectedTransaction: "Ops cycle → preuves de session → M5_DECISION stratégique → COMPLIANCE_M5",
      status: "Peak Week — mission 3/3 · bilan du quart",
      warehouse: "CDC Montréal",
    },
    successCriteria: [
      "≥3 preuves de session",
      "Diagnostic + priorité + compromis + horizon + recommandation",
      "Score ≥ 70",
    ],
    failureConditions: ["Portfolio M4 seul", "Texte générique sans preuves", "Dimension obligatoire absente"],
    wmsFunction: "Shift review / strategic defense",
    sapEquivalent: "Ops review with warehouse evidence",
    odooEquivalent: "Executive ops debrief",
    industryRelevance: "Bilan de quart superviseur.",
    demoGuidance: "En démo, explorez la structure de défense avec le moniteur de session.",
    evalGuidance:
      "Exiger ≥3 preuves de session + 6 dimensions. Rejeter 6×/95 %/4 % et tout OTIF/backlog inventé.",
    recoveryPaths: ["Relire le moniteur de session puis reformuler"],
    alternativeActions: [
      "Coller le portfolio M4 Annexe A",
      "Inventer un OTIF ou un backlog non produit par le runtime",
    ],
    wrongActionConsequences: ["Défense rejetée — preuves non valides"],
  },
};
