import type { MissionData } from "./missionData";

/** Static display content for SCN-006 to SCN-017 (M2–M5). No scenario logic. */
export const EXTENDED_MISSIONS: Record<string, MissionData> = {
  "SCN-006": {
    scenarioId: 6,
    scnCode: "SCN-006",
    objective: "Exécuter un rangement structuré depuis le quai vers un emplacement STOCKAGE conforme aux règles de capacité.",
    context:
      "150 unités SKU-001 sont déjà réceptionnées et postées au quai REC-01 (PO-M2-001 / GR-M2-001 visibles dans le moniteur). Votre mission : observer le stock au quai, valider la GR, puis affecter un emplacement définitif en zone STOCKAGE selon les règles LT01.",
    role: "Spécialiste Rangement (Putaway Specialist)",
    module: "WM — Exécution d'entrepôt",
    controlPoints: [
      "Vérifier dans le moniteur que la GR est postée avant tout rangement.",
      "Confirmer que REC-01 contient 150 u. SKU-001 dans le cockpit.",
      "Choisir un bin destination en zone STOCKAGE respectant la capacité.",
      "Valider la précision stock avant conformité avancée.",
    ],
    studentActions: [
      "Observer le moniteur : PO-M2-001 et GR-M2-001 doivent être POSTED.",
      "Ouvrir le cockpit : confirmer 150 u. SKU-001 au quai REC-01.",
      "Exécuter PUTAWAY (LT01) : REC-01 → bin STOCKAGE valide.",
      "Compléter FIFO_PICK et STOCK_ACCURACY selon les étapes du flux M2.",
      "Valider COMPLIANCE_ADV une fois toutes les étapes terminées.",
    ],
    expectedOutcome: "Marchandise rangée en STOCKAGE, stock précis, conformité M2 validée.",
    supervisorNotes:
      "Flux M2 : GR → PUTAWAY → FIFO_PICK → STOCK_ACCURACY → COMPLIANCE_ADV. Ne pas sauter PUTAWAY tant que le stock est au quai.",
    technicalSpecs: {
      sku: "SKU-001",
      quantity: 150,
      sourceBin: "REC-01",
      targetBin: "Zone STOCKAGE (bin valide)",
      expectedTransaction: "PUTAWAY (LT01) — REC-01 → STOCKAGE",
      status: "GR postée — stock au quai",
    },
    successCriteria: ["Putaway vers bin STOCKAGE valide", "Séquence M2 respectée", "Score ≥ 60 en évaluation"],
    failureConditions: ["Putaway sans GR postée", "Bin hors zone STOCKAGE", "Séquence hors ordre"],
    wmsFunction: "Putaway / slotting",
    sapEquivalent: "LT01, LT12, WM-TO",
    odooEquivalent: "Internal Transfers, Putaway rules",
    industryRelevance: "Slotting et traçabilité emplacement en entrepôt automatisé.",
    demoGuidance: "Explorez les capacités bin sans pénalité officielle.",
    evalGuidance: "Chaque erreur de zone ou séquence est pénalisée et compte pour la certification M2.",
    recoveryPaths: ["Choisir un bin alternatif si capacité dépassée"],
    alternativeActions: ["Ranger en zone non-STOCKAGE sans vérifier les règles d'emplacement"],
    wrongActionConsequences: ["Putaway hors zone → pénalité OUT_OF_SEQUENCE"],
  },
  "SCN-007": {
    scenarioId: 7,
    scnCode: "SCN-007",
    objective: "Gérer un dépassement de capacité d'emplacement et proposer une solution conforme.",
    context:
      "600 unités SKU-002 sont reçues et postées au quai REC-01. Le bin B-01-R1-L1 accepte maximum 500 unités. Observez le message de dépassement, validez la contrainte, puis répartissez le stock sans overflow.",
    role: "Planificateur Capacité (Capacity Planner)",
    module: "WM — Gestion des emplacements",
    controlPoints: [
      "Identifier la capacité max du bin cible (500 u.) avant validation.",
      "Détecter l'alerte overflow si 600 u. sont forcées dans un seul bin.",
      "Répartir sur plusieurs bins STOCKAGE valides.",
      "Maintenir la traçabilité lot LOT-2025-002.",
    ],
    studentActions: [
      "Vérifier REC-01 : 600 u. SKU-002 postées (GR-M2-002).",
      "Tenter ou simuler PUTAWAY vers B-01-R1-L1 — observer l'alerte capacité.",
      "Répartir le stock sur B-01-R1-L1 (500 u.) + bin STOCKAGE secondaire.",
      "Compléter FIFO_PICK, STOCK_ACCURACY, COMPLIANCE_ADV.",
    ],
    expectedOutcome: "Stock réparti sans overflow, précision validée, conformité M2.",
    supervisorNotes: "Le système doit refuser ou alerter sur un dépassement de 500 u. dans B-01-R1-L1.",
    technicalSpecs: {
      sku: "SKU-002",
      quantity: 600,
      sourceBin: "REC-01",
      targetBin: "B-01-R1-L1 (max 500) + bin STOCKAGE alternatif",
      expectedTransaction: "PUTAWAY split — overflow management",
      status: "GR postée — capacité à valider",
    },
    successCriteria: ["Aucun bin au-delà de sa capacité", "Toutes unités rangées", "Traçabilité lot conservée"],
    failureConditions: ["Single-bin overflow", "Perte de traçabilité lot"],
    wmsFunction: "Bin capacity control",
    sapEquivalent: "LS01, capacity checks in WM",
    odooEquivalent: "Storage capacity, location constraints",
    industryRelevance: "Éviter saturation slots en e-commerce haute rotation.",
    demoGuidance: "Testez plusieurs bins pour voir les messages capacité.",
    evalGuidance: "La répartition correcte est obligatoire pour valider le scénario.",
    recoveryPaths: ["Utiliser bin secondaire en STOCKAGE"],
    alternativeActions: [
      "Forcer les 600 unités dans un seul bin malgré l'alerte capacité",
      "Ignorer le message de dépassement et valider le putaway",
    ],
    wrongActionConsequences: ["Capacité dépassée → erreur opérationnelle et pénalité"],
  },
  "SCN-008": {
    scenarioId: 8,
    scnCode: "SCN-008",
    objective: "Appliquer FIFO sur trois lots du même SKU lors du rangement et du prélèvement.",
    context:
      "Trois lots SKU-003 sont déjà en stock multi-bins : LOT-A (jan, B-01-R1-L1), LOT-B (fév, B-01-R1-L2), LOT-C (mars, B-02-R1-L1). Observez les dates de réception dans le cockpit, validez l'ordre FIFO, puis prélevez le lot le plus ancien en premier.",
    role: "Spécialiste FIFO",
    module: "WM — Traçabilité lots",
    controlPoints: [
      "Comparer les dates de réception des trois lots dans le cockpit.",
      "Confirmer que LOT-A-2025 est le lot le plus ancien.",
      "Prélever LOT-A avant LOT-B et LOT-C lors du FIFO_PICK.",
      "Ne pas mélanger les lots dans un même mouvement.",
    ],
    studentActions: [
      "Observer le stock : 3 lots SKU-003 répartis sur B-01-R1-L1, B-01-R1-L2, B-02-R1-L1.",
      "Valider l'ordre FIFO : LOT-A (jan) → LOT-B (fév) → LOT-C (mars).",
      "Exécuter PUTAWAY si requis, puis FIFO_PICK sur le lot le plus ancien.",
      "Compléter STOCK_ACCURACY et COMPLIANCE_ADV.",
    ],
    expectedOutcome: "Prélèvement conforme FIFO, traçabilité lot intacte.",
    supervisorNotes: "LOT-A (jan) doit sortir avant LOT-B et LOT-C. Violation FIFO = échec conformité.",
    technicalSpecs: {
      sku: "SKU-003",
      quantity: 300,
      sourceBin: "B-01-R1-L1 / B-01-R1-L2 / B-02-R1-L1",
      targetBin: "Zone EXPÉDITION (FIFO_PICK)",
      expectedTransaction: "FIFO_PICK — LOT-A-2025 en premier",
      status: "3 lots postés — ordre jan/fév/mars",
    },
    successCriteria: ["Lot oldest picked first", "Traçabilité lot conservée"],
    failureConditions: ["Pick lot récent avant ancien", "Mélange lots non autorisé"],
    wmsFunction: "FIFO / FEFO picking",
    sapEquivalent: "FIFO strategy, batch determination",
    odooEquivalent: "Removal strategy FIFO, lots",
    industryRelevance: "Conformité alimentaire/pharma et réduction obsolescence.",
    demoGuidance: "Comparez dates de réception des lots dans le cockpit.",
    evalGuidance: "Mauvais lot = pénalité FIFO et échec conformité.",
    recoveryPaths: ["Re-pick avec lot correct si erreur en démo"],
    alternativeActions: [
      "Prélever LOT-C avant LOT-A — violation FIFO client",
      "Mélanger deux lots dans un même mouvement",
    ],
    wrongActionConsequences: ["Violation FIFO → pénalité et client non servi correctement"],
  },
  "SCN-009": {
    scenarioId: 9,
    scnCode: "SCN-009",
    objective: "Réaliser un inventaire cyclique simple et identifier les écarts système/physique.",
    context:
      "Stock système préchargé : SKU-001 = 100 u. (B-01-R1-L1), SKU-003 = 80 u. (B-01-R1-L2). Le comptage physique révélera un écart de −3 sur SKU-001. Observez les quantités système, saisissez les quantités physiques réelles, puis réconciliez.",
    role: "Auditeur Inventaire (Inventory Auditor)",
    module: "IM — Inventaire cyclique",
    controlPoints: [
      "Générer la liste de comptage (CC_LIST) complète.",
      "Saisir les quantités physiques exactes au CC_COUNT.",
      "Identifier l'écart −3 sur SKU-001 à la réconciliation.",
      "Documenter avant tout ajustement.",
    ],
    studentActions: [
      "CC_LIST : identifier SKU-001 et SKU-003 à compter.",
      "CC_COUNT : saisir quantités physiques (SKU-001 ≠ 100, SKU-003 = 80).",
      "CC_RECON : analyser l'écart −3 sur SKU-001.",
      "REPLENISH si besoin, puis COMPLIANCE_M3.",
    ],
    expectedOutcome: "Écart −3 identifié et réconcilié, conformité M3 validée.",
    supervisorNotes: "L'écart −3 sur SKU-001 est intentionnel — ne pas ignorer à la réconciliation.",
    technicalSpecs: {
      sku: "SKU-001 / SKU-003",
      quantity: "100 / 80 (système)",
      sourceBin: "B-01-R1-L1 / B-01-R1-L2",
      targetBin: "N/A — comptage sur place",
      expectedTransaction: "CC_COUNT → CC_RECON",
      status: "Écart −3 attendu sur SKU-001",
    },
    successCriteria: ["Écart détecté", "Réconciliation documentée", "Score ≥ 70"],
    failureConditions: ["Ignorer écart", "Ajuster sans justification"],
    wmsFunction: "Cycle counting",
    sapEquivalent: "MI01, MI04, MI07",
    odooEquivalent: "Inventory adjustments, cycle counts",
    industryRelevance: "Inventaire perpétuel vs arrêt annuel.",
    demoGuidance: "Pratiquez la saisie MI01 sans impact certification.",
    evalGuidance: "Justification requise pour tout ajustement significatif.",
    recoveryPaths: ["Re-saisir quantité physique correcte"],
    wrongActionConsequences: ["Écart non résolu bloque COMPLIANCE_M3"],
  },
  "SCN-010": {
    scenarioId: 10,
    scnCode: "SCN-010",
    objective: "Analyser un écart significatif (−28) et produire un ajustement justifié.",
    context:
      "SKU-006 : stock système 380 u. (B-02-R1-L1) après expédition partielle. Le comptage physique révèle 352 u. — écart de −28, au-delà du seuil d'ajustement (20 u.). Observez l'écart, justifiez la cause, puis ajustez.",
    role: "Gestionnaire Inventaire",
    module: "IM — Variance management",
    controlPoints: [
      "Confirmer stock système 380 u. avant comptage.",
      "Saisir quantité physique réelle (352 u.) au CC_COUNT.",
      "Documenter l'écart −28 (> seuil 20) à CC_RECON.",
      "Poster l'ajustement ADJ avec justification.",
    ],
    studentActions: [
      "CC_LIST : cibler SKU-006 / B-02-R1-L1.",
      "CC_COUNT : saisir 352 u. (physique) vs 380 u. (système).",
      "CC_RECON : justifier l'écart −28 (seuil dépassé).",
      "REPLENISH si requis, puis COMPLIANCE_M3.",
    ],
    expectedOutcome: "Variance −28 justifiée et ajustée, conformité verte.",
    supervisorNotes: "Ne pas ajuster sans analyse — seuil interne = 20 unités.",
    technicalSpecs: {
      sku: "SKU-006",
      quantity: 380,
      sourceBin: "B-02-R1-L1",
      targetBin: "N/A — ajustement sur place",
      expectedTransaction: "CC_RECON + ADJ (MI07) — écart −28",
      status: "Variance significative — justification requise",
    },
    successCriteria: ["Justification fournie", "ADJ posté", "Conformité verte"],
    failureConditions: ["ADJ sans justification", "Ignorer écart > seuil"],
    wmsFunction: "Variance analysis & adjustment",
    sapEquivalent: "MI07, difference analysis",
    odooEquivalent: "Inventory valuation adjustment",
    industryRelevance: "Réconciliation mensuelle comptabilité/stocks.",
    demoGuidance: "Testez différentes justifications en mode démo.",
    evalGuidance: "Justification obligatoire pour SCN-010 en évaluation.",
    recoveryPaths: ["Documenter cause racine puis ADJ"],
    alternativeActions: [
      "Ajuster l'écart −28 sans justification écrite",
      "Passer COMPLIANCE_M3 sans résoudre l'écart documenté",
    ],
    wrongActionConsequences: ["Ajustement non conforme → audit trail incomplet"],
  },
  "SCN-011": {
    scenarioId: 11,
    scnCode: "SCN-011",
    objective: "Générer des recommandations de réapprovisionnement selon Min/Max et stock de sécurité.",
    context:
      "Niveaux actuels : SKU-004 = 30 u. (Min 50, Max 200, SS 25) et SKU-005 = 40 u. (Min 80, Max 300, SS 30). Les deux SKU sont sous le seuil Min. Analysez les paramètres, calculez le besoin, puis générez les recommandations REPLENISH.",
    role: "Planificateur Approvisionnement (Supply Planner)",
    module: "MRP / Replenishment",
    controlPoints: [
      "Détecter SKU-004 et SKU-005 sous seuil Min.",
      "Consulter paramètres Min/Max/SS et lead time.",
      "Calculer quantités de réapprovisionnement (Min–Max : Q = Max − stock actuel).",
      "Valider REPLENISH avec quantités cohérentes.",
    ],
    studentActions: [
      "CC pipeline : confirmer niveaux SKU-004 (30) et SKU-005 (40).",
      "Comparer aux seuils Min (50 / 80) et SS (25 / 30).",
      "REPLENISH : proposer quantités pour atteindre le stock Max (Q = Max − stock actuel) pour chaque SKU.",
      "COMPLIANCE_M3 une fois recommandations validées.",
    ],
    expectedOutcome: "Suggestions de réappro conformes Min/Max, conformité M3.",
    supervisorNotes: "SKU-004 et SKU-005 nécessitent réappro — ne pas sous-estimer le besoin.",
    technicalSpecs: {
      sku: "SKU-004 / SKU-005",
      quantity: "30 / 40 (sous Min)",
      sourceBin: "B-01-R1-L1 / B-01-R1-L2",
      targetBin: "N/A — recommandation achat",
      expectedTransaction: "REPLENISH — Min-Max (Q = Max − stock)",
      status: "Sous seuil Min — réappro requis",
    },
    successCriteria: ["Seuils Min/Max respectés", "Quantités recommandées cohérentes"],
    failureConditions: ["Sous-réapprovisionnement", "Ignorer stock de sécurité"],
    wmsFunction: "Replenishment planning",
    sapEquivalent: "MD04, reorder point",
    odooEquivalent: "Reordering rules, Min/Max",
    industryRelevance: "Éviter ruptures tout en limitant stock dormant.",
    demoGuidance: "Comparez formules Min/Max dans le panneau learning.",
    evalGuidance: "Calculs ROP/EOQ évalués en mode officiel.",
    recoveryPaths: ["Recalculer besoin net puis REPLENISH"],
    alternativeActions: [
      "Réapprovisionner en quantité inférieure au besoin calculé",
      "Ignorer le stock de sécurité dans le calcul ROP",
    ],
    wrongActionConsequences: ["Rupture client si réappro insuffisant"],
  },
  "SCN-012": {
    scenarioId: 12,
    scnCode: "SCN-012",
    objective: "Calculer et interpréter le taux de rotation des stocks pour détecter surstock.",
    context:
      "Module analytique M4 : données KPI préchargées dans le control tower. Observez consommation annuelle vs stock moyen, calculez la rotation, puis interprétez si le niveau indique surstock ou sous-performance. Aucune transaction physique.",
    role: "Analyste Logistique",
    module: "CO-PA / Logistics controlling",
    controlPoints: [
      "Collecter les données KPI_DATA avant calcul.",
      "Appliquer la formule rotation (consommation / stock moyen).",
      "Comparer au benchmark 4–12×/an.",
      "Formuler une interprétation et recommandation.",
    ],
    studentActions: [
      "KPI_DATA : consulter les indicateurs préchargés.",
      "KPI_ROTATION : calculer et interpréter le taux de rotation.",
      "KPI_SERVICE puis KPI_DIAGNOSTIC : synthèse rotation.",
      "COMPLIANCE_M4 une fois diagnostic validé.",
    ],
    expectedOutcome: "Diagnostic rotation validé avec recommandation actionnable.",
    supervisorNotes: "M4 est analytique — pas de transactions physiques. Seuil passage 70/100.",
    technicalSpecs: {
      sku: "N/A — analyse portefeuille",
      quantity: "KPI-driven",
      sourceBin: "N/A",
      targetBin: "N/A",
      expectedTransaction: "KPI_DATA → KPI_ROTATION → KPI_DIAGNOSTIC",
      status: "Données KPI préchargées — mode analytique",
    },
    successCriteria: ["Formule rotation correcte", "Interprétation métier pertinente"],
    failureConditions: ["Calcul erroné", "Diagnostic sans données"],
    wmsFunction: "KPI analytics",
    sapEquivalent: "MC$4, Inventory turnover reports",
    odooEquivalent: "Inventory reports, stock valuation",
    industryRelevance: "Optimisation working capital.",
    demoGuidance: "Explorez les formules KPI en démo.",
    evalGuidance: "Seuil passage 70/100 — interprétation évaluée.",
    recoveryPaths: ["Recalculer avec données KPI_DATA"],
    alternativeActions: [
      "Interpréter la rotation sans consulter KPI_DATA",
      "Conclure surstock sans appliquer la formule rotation",
    ],
    wrongActionConsequences: ["Mauvaise décision surstock → coût carrying excessif"],
  },
  "SCN-013": {
    scenarioId: 13,
    scnCode: "SCN-013",
    objective: "Diagnostiquer un faible taux de service et l'impact des erreurs opérationnelles.",
    context:
      "Indicateurs service level et error rate fournis dans le control tower. Observez le taux de service (< 95 %), corrélez avec les erreurs picking/réception, puis proposez un plan d'action. Module analytique — pas de mouvement stock.",
    role: "Responsable Performance",
    module: "Logistics Performance Management",
    controlPoints: [
      "Analyser le taux de service vs cible ≥ 95 %.",
      "Corréler erreurs opérationnelles (picking, réception) au SLA.",
      "Identifier causes racines dans KPI_SERVICE.",
      "Proposer plan d'action dans KPI_DIAGNOSTIC.",
    ],
    studentActions: [
      "KPI_DATA : charger indicateurs service et erreurs.",
      "KPI_ROTATION : contexte portefeuille si requis.",
      "KPI_SERVICE : analyser OTIF et taux d'erreur.",
      "KPI_DIAGNOSTIC → COMPLIANCE_M4.",
    ],
    expectedOutcome: "Diagnostic service level avec causes et actions actionnables.",
    supervisorNotes: "Relier erreurs picking/receiving au taux de service — pas de diagnostic générique.",
    technicalSpecs: {
      sku: "N/A — indicateurs agrégés",
      quantity: "KPI service + erreurs",
      sourceBin: "N/A",
      targetBin: "N/A",
      expectedTransaction: "KPI_SERVICE → KPI_DIAGNOSTIC",
      status: "Service < cible — analyse causes requise",
    },
    successCriteria: ["Causes identifiées", "Recommandations actionnables"],
    failureConditions: ["Diagnostic générique sans données"],
    wmsFunction: "Service level monitoring",
    sapEquivalent: "OTIF, VL06O performance",
    odooEquivalent: "Delivery performance, SLA dashboards",
    industryRelevance: "OTIF contractuel grands comptes.",
    demoGuidance: "Testez scénarios what-if en démo.",
    evalGuidance: "Évaluation sur qualité du diagnostic.",
    recoveryPaths: ["Réanalyser corrélation erreurs/KPI"],
    alternativeActions: [
      "Diagnostiquer sans corréler les erreurs opérationnelles",
      "Proposer un plan d'action sans indicateurs chiffrés",
    ],
    wrongActionConsequences: ["Mauvais levier d'amélioration → SLA non atteint"],
  },
  "SCN-014": {
    scenarioId: 14,
    scnCode: "SCN-014",
    objective: "Synthétiser plusieurs KPI et formuler une décision stratégique logistique.",
    context:
      "Capstone M4 : rotation, service, erreurs et lead time combinés dans le control tower. Analysez les trade-offs stock/service/coût, identifiez le levier prioritaire, puis formulez une décision stratégique justifiée.",
    role: "Directeur des Opérations",
    module: "Strategic Logistics Control Tower",
    controlPoints: [
      "Analyser tous les KPI (rotation, service, erreurs, lead time).",
      "Identifier trade-offs — pas d'analyse mono-indicateur.",
      "Formuler décision stratégique dans KPI_DIAGNOSTIC.",
      "Valider COMPLIANCE_M4 avec synthèse complète.",
    ],
    studentActions: [
      "Pipeline KPI complet : DATA → ROTATION → SERVICE.",
      "KPI_DIAGNOSTIC : décision stratégique multi-indicateurs.",
      "COMPLIANCE_M4 une fois décision argumentée.",
    ],
    expectedOutcome: "Décision stratégique documentée et conforme.",
    supervisorNotes: "Capstone M4 — niveau Evaluate. Seuil 70/100.",
    technicalSpecs: {
      sku: "N/A — multi-KPI",
      quantity: "Rotation + service + erreurs + lead time",
      sourceBin: "N/A",
      targetBin: "N/A",
      expectedTransaction: "KPI_DIAGNOSTIC stratégique → COMPLIANCE_M4",
      status: "Synthèse multi-indicateurs requise",
    },
    successCriteria: ["Synthèse multi-indicateurs", "Décision argumentée"],
    failureConditions: ["Analyse mono-KPI", "Décision sans justification"],
    wmsFunction: "Integrated performance diagnosis",
    sapEquivalent: "Embedded analytics, SAC",
    odooEquivalent: "Spreadsheet / BI dashboards",
    industryRelevance: "S&OP et revue performance mensuelle.",
    demoGuidance: "Comparez plusieurs options stratégiques en démo.",
    evalGuidance: "Seuil 70/100 — qualité décision évaluée.",
    recoveryPaths: ["Revoir trade-offs stock/service/coût"],
    alternativeActions: [
      "Décision basée sur un seul KPI — ignore les trade-offs",
      "Recommandation sans justification liée aux KPI combinés",
    ],
    wrongActionConsequences: ["Décision sous-optimale → perte compétitivité"],
  },
  "SCN-015": {
    scenarioId: 15,
    scnCode: "SCN-015",
    objective: "Exécuter un cycle opérationnel intégré fournisseur → entrepôt → client.",
    context:
      "Capstone opérationnel M5 : enchaîner réception fournisseur, rangement FIFO, inventaire cyclique, réapprovisionnement, calcul KPI et décision stratégique. Observez chaque étape dans le moniteur et le cockpit avant de valider la suivante.",
    role: "Gestionnaire d'Entrepôt",
    module: "Integrated WM + IM + KPI",
    controlPoints: [
      "M5_RECEPTION : valider réception fournisseur postée.",
      "M5_PUTAWAY : rangement FIFO conforme.",
      "M5_CYCLE_COUNT : écarts identifiés et traités.",
      "M5_REPLENISH → M5_KPI → M5_DECISION → COMPLIANCE_M5.",
    ],
    studentActions: [
      "M5_RECEPTION : observer et valider la réception.",
      "M5_PUTAWAY : ranger en respectant FIFO.",
      "M5_CYCLE_COUNT : compter et réconcilier.",
      "M5_REPLENISH : réappro si sous seuil.",
      "M5_KPI → M5_DECISION → COMPLIANCE_M5.",
    ],
    expectedOutcome: "Cycle intégré complété, conformité M5 validée.",
    supervisorNotes: "Capstone opérationnel avant certification Gold. Chaque étape compte.",
    technicalSpecs: {
      sku: "Multi-SKU",
      quantity: "Variable par étape",
      sourceBin: "REC-01 → STOCKAGE",
      targetBin: "STOCKAGE → EXPÉDITION",
      expectedTransaction: "M5_RECEPTION → M5_PUTAWAY → M5_CYCLE_COUNT → M5_REPLENISH → M5_KPI → M5_DECISION",
      status: "Cycle intégré — 7 étapes M5",
    },
    successCriteria: ["7 étapes M5 complétées", "Conformité finale", "Score ≥ 70"],
    failureConditions: ["Écart non résolu", "Décision KPI incohérente"],
    wmsFunction: "End-to-end warehouse orchestration",
    sapEquivalent: "EWM integrated scenario",
    odooEquivalent: "Full warehouse workflow",
    industryRelevance: "Pilotage entrepôt omnicanal.",
    demoGuidance: "Parcourez le flux complet sans pression certification.",
    evalGuidance: "Chaque étape compte pour progression M5 et Gold.",
    recoveryPaths: ["Corriger écart inventaire avant décision"],
    alternativeActions: [
      "Sauter M5_REPLENISH ou M5_CYCLE_COUNT pour aller au KPI",
      "Clôturer COMPLIANCE_M5 avec écart inventaire ouvert",
    ],
    wrongActionConsequences: ["Incohérence flux → KPI final faussé"],
  },
  "SCN-016": {
    scenarioId: 16,
    scnCode: "SCN-016",
    objective: "Gérer des écarts d'inventaire en cours de simulation intégrée et appliquer corrections.",
    context:
      "Cycle M5 avec variance injectée au comptage. Observez l'écart dans M5_CYCLE_COUNT, corrigez via ajustement avant M5_KPI et M5_DECISION. Ne pas clôturer tant que l'écart physique n'est pas résolu.",
    role: "Gestionnaire d'Entrepôt",
    module: "Corrective warehouse control",
    controlPoints: [
      "Détecter variance au M5_CYCLE_COUNT.",
      "Corriger via ADJ avant M5_KPI.",
      "Maintenir traçabilité de l'ajustement.",
      "Décision KPI post-correction uniquement.",
    ],
    studentActions: [
      "M5_RECEPTION → M5_PUTAWAY : flux standard.",
      "M5_CYCLE_COUNT : identifier l'écart injecté.",
      "Corriger l'écart (ADJ) avant M5_REPLENISH.",
      "M5_KPI → M5_DECISION → COMPLIANCE_M5.",
    ],
    expectedOutcome: "Écarts corrigés, simulation clôturée conforme.",
    supervisorNotes: "Priorité : résoudre physique avant décision KPI.",
    technicalSpecs: {
      sku: "Variable (écart injecté)",
      quantity: "Système ≠ physique",
      sourceBin: "STOCKAGE (bin concerné)",
      targetBin: "N/A — ajustement sur place",
      expectedTransaction: "M5_CYCLE_COUNT → ADJ → M5_KPI",
      status: "Variance injectée — correction requise",
    },
    successCriteria: ["Variance résolue", "Décision post-correction"],
    failureConditions: ["Compliance avec écart ouvert", "ADJ manquant"],
    wmsFunction: "Exception management",
    sapEquivalent: "MI07 in integrated flow",
    odooEquivalent: "Inventory adjustment wizard",
    industryRelevance: "Gestion exceptions temps réel en ops.",
    demoGuidance: "Rejouez la branche CC→ADJ en démo.",
    evalGuidance: "Correction obligatoire en évaluation.",
    recoveryPaths: ["CC → ADJ → reprise flux"],
    alternativeActions: [
      "Passer à M5_KPI sans corriger l'écart physique",
      "Valider COMPLIANCE_M5 avant ADJ requis",
    ],
    wrongActionConsequences: ["Stock incorrect → décision KPI erronée"],
  },
  "SCN-017": {
    scenarioId: 17,
    scnCode: "SCN-017",
    objective: "Analyser les KPI globaux et formuler une décision stratégique justifiée.",
    context:
      "Capstone M5 décisionnel : après le cycle opérationnel, indicateurs agrégés disponibles dans M5_KPI. Analysez le portefeuille KPI, formulez M5_DECISION avec justification chiffrée, puis validez COMPLIANCE_M5.",
    role: "Directeur Logistique",
    module: "Strategic decision layer",
    controlPoints: [
      "Consulter indicateurs M5_KPI agrégés.",
      "Lier décision aux données chiffrées.",
      "Justifier orientation stratégique entrepôt.",
      "COMPLIANCE_M5 après décision complète.",
    ],
    studentActions: [
      "Compléter étapes ops amont si requises.",
      "M5_KPI : analyser indicateurs agrégés.",
      "M5_DECISION : formulation stratégique justifiée.",
      "COMPLIANCE_M5 : validation finale Gold-path.",
    ],
    expectedOutcome: "Décision stratégique validée, conformité Gold-path.",
    supervisorNotes: "Niveau Bloom : Create — justification essentielle pour certification Gold.",
    technicalSpecs: {
      sku: "Portfolio multi-SKU",
      quantity: "KPI agrégés post-cycle",
      sourceBin: "N/A",
      targetBin: "N/A",
      expectedTransaction: "M5_KPI → M5_DECISION → COMPLIANCE_M5",
      status: "Décision stratégique finale requise",
    },
    successCriteria: ["Décision argumentée", "KPI cohérents", "Conformité M5"],
    failureConditions: ["Décision sans lien KPI", "Compliance prématurée"],
    wmsFunction: "Strategic warehouse decision support",
    sapEquivalent: "IBP / analytics tie-in",
    odooEquivalent: "Executive dashboard decision",
    industryRelevance: "Comité logistique direction.",
    demoGuidance: "Explorez options décision en mode démo.",
    evalGuidance: "Décision finale évaluée pour certification Gold path.",
    recoveryPaths: ["Revoir KPI puis reformuler décision"],
    alternativeActions: [
      "M5_DECISION sans lien aux indicateurs M5_KPI",
      "COMPLIANCE_M5 avant synthèse stratégique complète",
    ],
    wrongActionConsequences: ["Mauvaise orientation stratégique entrepôt"],
  },
};
