import type { MissionData } from "./missionData";

/** Static display content for SCN-006 to SCN-017 (M2–M5). No scenario logic. */
export const EXTENDED_MISSIONS: Record<string, MissionData> = {
  "SCN-006": {
    scenarioId: 6,
    scnCode: "SCN-006",
    objective: "Exécuter un rangement structuré depuis le quai vers un emplacement STOCKAGE conforme aux règles de capacité.",
    context: "150 unités SKU-001 reçues et postées au quai REC-01. Vous devez affecter l'emplacement définitif selon les règles LT01.",
    role: "Spécialiste Rangement (Putaway Specialist)",
    module: "WM — Exécution d'entrepôt",
    controlPoints: ["GR postée avant putaway", "Bin destination en zone STOCKAGE", "Capacité respectée"],
    studentActions: ["Valider la GR", "Ranger REC-01 → bin STOCKAGE (LT01)", "Prélèvement FIFO si requis", "Valider précision stock", "Conformité avancée"],
    expectedOutcome: "Marchandise rangée, stock précis, conformité M2 validée.",
    supervisorNotes: "Flux M2 : GR → PUTAWAY → FIFO_PICK → STOCK_ACCURACY → COMPLIANCE_ADV.",
    technicalSpecs: { sku: "SKU-001", quantity: 150, suggestedBin: "REC-01" },
    successCriteria: ["Putaway vers bin valide", "FIFO respecté si applicable", "Score ≥ 60 en évaluation"],
    failureConditions: ["Dépassement capacité bin", "Mauvaise zone", "Séquence hors ordre"],
    wmsFunction: "Putaway / slotting",
    sapEquivalent: "LT01, LT12, WM-TO",
    odooEquivalent: "Internal Transfers, Putaway rules",
    industryRelevance: "Slotting et traçabilité emplacement en entrepôt automatisé.",
    demoGuidance: "Explorez les capacités bin sans pénalité officielle.",
    evalGuidance: "Chaque erreur de zone ou séquence est pénalisée et compte pour la certification M2.",
    recoveryPaths: ["Choisir un bin alternatif si capacité dépassée"],
    alternativeActions: ["Ranger en plusieurs bins si capacité insuffisante"],
    wrongActionConsequences: ["Putaway over-cap → blocage et pénalité OUT_OF_SEQUENCE"],
  },
  "SCN-007": {
    scenarioId: 7,
    scnCode: "SCN-007",
    objective: "Gérer un dépassement de capacité d'emplacement et proposer une solution conforme.",
    context: "600 unités SKU-002 reçues. Le bin B-01-R1-L1 a une capacité de 500 unités.",
    role: "Planificateur Capacité (Capacity Planner)",
    module: "WM — Gestion des emplacements",
    controlPoints: ["Détecter overflow avant validation", "Répartir sur bins valides", "Maintenir traçabilité lot"],
    studentActions: ["Identifier capacité max", "Split putaway si nécessaire", "FIFO pick", "Stock accuracy", "Compliance"],
    expectedOutcome: "Stock réparti sans overflow, précision validée.",
    supervisorNotes: "Le système doit refuser ou alerter sur un dépassement de 500 u.",
    technicalSpecs: { sku: "SKU-002", quantity: 600, suggestedBin: "B-01-R1-L1" },
    successCriteria: ["Aucun bin au-delà de sa capacité", "Toutes unités rangées"],
    failureConditions: ["Single-bin overflow", "Perte de traçabilité"],
    wmsFunction: "Bin capacity control",
    sapEquivalent: "LS01, capacity checks in WM",
    odooEquivalent: "Storage capacity, location constraints",
    industryRelevance: "Éviter saturation slots en e-commerce haute rotation.",
    demoGuidance: "Testez plusieurs bins pour voir les messages capacité.",
    evalGuidance: "La répartition correcte est obligatoire pour valider le scénario.",
    recoveryPaths: ["Utiliser bin secondaire en STOCKAGE"],
    alternativeActions: [
      "Forcer les 600 unités dans un seul bin malgré l'alerte capacité — le système bloque et la traçabilité est compromise",
      "Ignorer le message de dépassement et valider le putaway — erreur opérationnelle et pénalité en évaluation",
      "Ranger en zone non-STOCKAGE sans vérifier les règles d'emplacement",
    ],
    wrongActionConsequences: ["Capacité dépassée → erreur opérationnelle et pénalité"],
  },
  "SCN-008": {
    scenarioId: 8,
    scnCode: "SCN-008",
    objective: "Appliquer FIFO sur trois lots du même SKU lors du rangement et du prélèvement.",
    context: "Trois lots SKU-003 (jan, fév, mars) en stock multi-bins. Le client exige le lot le plus ancien.",
    role: "Spécialiste FIFO",
    module: "WM — Traçabilité lots",
    controlPoints: ["Ordre FIFO strict", "Lot le plus ancien prélevé en premier", "Pas de mélange lots"],
    studentActions: ["GR multi-lots", "Putaway par lot", "FIFO pick lot A", "Stock accuracy", "Compliance"],
    expectedOutcome: "Prélèvement conforme FIFO, traçabilité intacte.",
    supervisorNotes: "LOT-A (jan) doit sortir avant LOT-B et LOT-C.",
    technicalSpecs: { sku: "SKU-003", quantity: 300, suggestedBin: "Multi-bins" },
    successCriteria: ["Lot oldest picked first", "Traçabilité lot conservée"],
    failureConditions: ["Pick lot récent avant ancien", "Mélange lots non autorisé"],
    wmsFunction: "FIFO / FEFO picking",
    sapEquivalent: "FIFO strategy, batch determination",
    odooEquivalent: "Removal strategy FIFO, lots",
    industryRelevance: "Conformité alimentaire/pharma et réduction obsolescence.",
    demoGuidance: "Comparez dates de réception des lots dans le cockpit.",
    evalGuidance: "Mauvais lot = pénalité FIFO et échec conformité.",
    recoveryPaths: ["Re-pick avec lot correct si erreur en démo"],
    alternativeActions: [
      "Prélever un lot récent (LOT-C) avant le lot le plus ancien (LOT-A) — violation FIFO client",
      "Mélanger deux lots dans un même mouvement sans séparation — perte de traçabilité",
      "Ignorer les dates de réception affichées et choisir un bin au hasard",
    ],
    wrongActionConsequences: ["Violation FIFO → pénalité et client non servi correctement"],
  },
  "SCN-009": {
    scenarioId: 9,
    scnCode: "SCN-009",
    objective: "Réaliser un inventaire cyclique simple et identifier les écarts système/physique.",
    context: "Stock système SKU-001 (100) et SKU-003 (80). Comptage physique révélera un écart de −3 sur SKU-001.",
    role: "Auditeur Inventaire (Inventory Auditor)",
    module: "IM — Inventaire cyclique",
    controlPoints: ["Liste de comptage complète", "Saisie quantités physiques exactes", "Réconciliation avant ajustement"],
    studentActions: ["CC_LIST", "CC_COUNT", "CC_RECON", "REPLENISH si besoin", "COMPLIANCE_M3"],
    expectedOutcome: "Écarts identifiés, réconciliés, conformité M3.",
    supervisorNotes: "Écart −3 SKU-001 est pédagogique.",
    technicalSpecs: { sku: "SKU-001 / SKU-003", quantity: "180 total", suggestedBin: "B-01-R1-L1" },
    successCriteria: ["Écart détecté", "Réconciliation documentée", "Score ≥ 70"],
    failureConditions: ["Ignorer écart", "Ajuster sans justification"],
    wmsFunction: "Cycle counting",
    sapEquivalent: "MI01, MI04, MI07",
    odooEquivalent: "Inventory adjustments, cycle counts",
    industryRelevance: "Inventaire perpétuel vs arrêt annuel.",
    demoGuidance: "Pratiquez la saisie MI01 sans impact certification.",
    evalGuidance: "Justification requise pour tout ajustement significatif.",
    recoveryPaths: ["Re-saisir quantité physique correcte"],
    wrongActionConsequences: ["Écart non résolu bloque COMPLIANCE_M3"],
  },
  "SCN-010": {
    scenarioId: 10,
    scnCode: "SCN-010",
    objective: "Analyser un écart significatif (−28) et produire un ajustement justifié.",
    context: "SKU-006 : système 380 u., physique 352 u. Seuil d'ajustement sans escalade : 20 u.",
    role: "Gestionnaire Inventaire",
    module: "IM — Variance management",
    controlPoints: ["Écart > seuil documenté", "Justification métier", "ADJ conforme"],
    studentActions: ["CC_LIST", "CC_COUNT", "CC_RECON avec justification", "REPLENISH", "COMPLIANCE_M3"],
    expectedOutcome: "Variance −28 justifiée et ajustée.",
    supervisorNotes: "Ne pas ajuster sans analyse.",
    technicalSpecs: { sku: "SKU-006", quantity: 380, suggestedBin: "B-02-R1-L1" },
    successCriteria: ["Justification fournie", "ADJ posté", "Conformité verte"],
    failureConditions: ["ADJ sans justification", "Ignorer écart > seuil"],
    wmsFunction: "Variance analysis & adjustment",
    sapEquivalent: "MI07, difference analysis",
    odooEquivalent: "Inventory valuation adjustment",
    industryRelevance: "Réconciliation mensuelle comptabilité/stocks.",
    demoGuidance: "Testez différentes justifications en mode démo.",
    evalGuidance: "Justification obligatoire pour SCN-010 en évaluation.",
    recoveryPaths: ["Documenter cause racine puis ADJ"],
    alternativeActions: [
      "Saisir une quantité physique arbitraire sans comptage réel — fausse la réconciliation",
      "Ajuster l'écart −28 sans justification écrite — non-conforme au seuil de 20 unités",
      "Passer REPLENISH ou COMPLIANCE_M3 sans résoudre l'écart documenté",
    ],
    wrongActionConsequences: ["Ajustement non conforme → audit trail incomplet"],
  },
  "SCN-011": {
    scenarioId: 11,
    scnCode: "SCN-011",
    objective: "Générer des recommandations de réapprovisionnement selon Min/Max et stock de sécurité.",
    context: "SKU-004 (30 u., Min 50) et SKU-005 (40 u., Min 80) sous seuil. Paramètres Min/Max/SS définis.",
    role: "Planificateur Approvisionnement (Supply Planner)",
    module: "MRP / Replenishment",
    controlPoints: ["Niveau sous Min détecté", "EOQ/ROP calculé", "Suggestion conforme paramètres"],
    studentActions: ["CC pipeline", "REPLENISH avec quantités calculées", "COMPLIANCE_M3"],
    expectedOutcome: "Suggestions de réappro conformes Min/Max.",
    supervisorNotes: "SKU-004 et SKU-005 nécessitent réappro.",
    technicalSpecs: { sku: "SKU-004 / SKU-005", quantity: "30 / 40", suggestedBin: "STOCKAGE" },
    successCriteria: ["ROP respecté", "Quantités recommandées cohérentes"],
    failureConditions: ["Sous-réapprovisionnement", "Ignorer stock de sécurité"],
    wmsFunction: "Replenishment planning",
    sapEquivalent: "MD04, reorder point",
    odooEquivalent: "Reordering rules, Min/Max",
    industryRelevance: "Éviter ruptures tout en limitant stock dormant.",
    demoGuidance: "Comparez formules Min/Max dans le panneau learning.",
    evalGuidance: "Calculs ROP/EOQ évalués en mode officiel.",
    recoveryPaths: ["Recalculer besoin net puis REPLENISH"],
    alternativeActions: [
      "Réapprovisionner en quantité inférieure au besoin calculé (sous Min) — risque rupture",
      "Ignorer le stock de sécurité dans le calcul ROP — sous-estimation du besoin",
      "Valider REPLENISH sans consulter les paramètres Min/Max des SKU concernés",
    ],
    wrongActionConsequences: ["Rupture client si réappro insuffisant"],
  },
  "SCN-012": {
    scenarioId: 12,
    scnCode: "SCN-012",
    objective: "Calculer et interpréter le taux de rotation des stocks pour détecter surstock.",
    context: "Données KPI fournies : analyser rotation et identifier surstock ou sous-performance.",
    role: "Analyste Logistique",
    module: "CO-PA / Logistics controlling",
    controlPoints: ["KPI_DATA collecté", "Rotation calculée", "Interprétation documentée"],
    studentActions: ["KPI_DATA", "KPI_ROTATION", "KPI_SERVICE", "KPI_DIAGNOSTIC", "COMPLIANCE_M4"],
    expectedOutcome: "Diagnostic rotation validé avec recommandation.",
    supervisorNotes: "M4 est analytique — pas de transactions physiques.",
    technicalSpecs: { sku: "N/A", quantity: "KPI-driven", suggestedBin: "N/A" },
    successCriteria: ["Formule rotation correcte", "Interprétation métier pertinente"],
    failureConditions: ["Calcul erroné", "Diagnostic sans données"],
    wmsFunction: "KPI analytics",
    sapEquivalent: "MC$4, Inventory turnover reports",
    odooEquivalent: "Inventory reports, stock valuation",
    industryRelevance: "Optimisation working capital.",
    demoGuidance: "Explorez les formules KPI en démo.",
    evalGuidance: "Seuil passage 70/100 — interprétation évaluée.",
    recoveryPaths: ["Recalculer avec données KPI_DATA"],
    alternativeActions: [
      "Interpréter la rotation sans consulter les données KPI_DATA — diagnostic non fondé",
      "Conclure surstock ou sous-performance sans appliquer la formule rotation — calcul erroné",
      "Passer KPI_DIAGNOSTIC avec une recommandation générique sans données chiffrées",
    ],
    wrongActionConsequences: ["Mauvaise décision surstock → coût carrying excessif"],
  },
  "SCN-013": {
    scenarioId: 13,
    scnCode: "SCN-013",
    objective: "Diagnostiquer un faible taux de service et l'impact des erreurs opérationnelles.",
    context: "Indicateurs service level et error rate fournis — identifier causes racines.",
    role: "Responsable Performance",
    module: "Logistics Performance Management",
    controlPoints: ["Taux service analysé", "Erreurs corrélées", "Plan d'action proposé"],
    studentActions: ["KPI_DATA", "KPI_ROTATION", "KPI_SERVICE", "KPI_DIAGNOSTIC", "COMPLIANCE_M4"],
    expectedOutcome: "Diagnostic service level avec causes et actions.",
    supervisorNotes: "Relier erreurs picking/receiving au taux de service.",
    technicalSpecs: { sku: "N/A", quantity: "KPI", suggestedBin: "N/A" },
    successCriteria: ["Causes identifiées", "Recommandations actionnables"],
    failureConditions: ["Diagnostic générique sans données"],
    wmsFunction: "Service level monitoring",
    sapEquivalent: "OTIF, VL06O performance",
    odooEquivalent: "Delivery performance, SLA dashboards",
    industryRelevance: "OTIF contractuel grands comptes.",
    demoGuidance: "Testez scénarios what-if en démo.",
    evalGuidance: "Évaluation sur qualité du diagnostic.",
    recoveryPaths: ["Réanalyser corrélation erreurs/KPI"],
    alternativeActions: [
      "Diagnostiquer le taux de service sans corréler les erreurs opérationnelles — causes manquées",
      "Proposer un plan d'action générique sans indicateurs chiffrés — non actionnable",
      "Ignorer le taux d'erreur dans l'analyse OTIF — mauvais levier d'amélioration",
    ],
    wrongActionConsequences: ["Mauvais levier d'amélioration → SLA non atteint"],
  },
  "SCN-014": {
    scenarioId: 14,
    scnCode: "SCN-014",
    objective: "Synthétiser plusieurs KPI et formuler une décision stratégique logistique.",
    context: "Rotation, service, erreurs et lead time combinés — décision globale requise.",
    role: "Directeur des Opérations",
    module: "Strategic Logistics Control Tower",
    controlPoints: ["Multi-KPI analysés", "Trade-offs identifiés", "Décision justifiée"],
    studentActions: ["Pipeline KPI complet", "KPI_DIAGNOSTIC stratégique", "COMPLIANCE_M4"],
    expectedOutcome: "Décision stratégique documentée et conforme.",
    supervisorNotes: "Capstone M4 — niveau Evaluate.",
    technicalSpecs: { sku: "N/A", quantity: "Multi-KPI", suggestedBin: "N/A" },
    successCriteria: ["Synthèse multi-indicateurs", "Décision argumentée"],
    failureConditions: ["Analyse mono-KPI", "Décision sans justification"],
    wmsFunction: "Integrated performance diagnosis",
    sapEquivalent: "Embedded analytics, SAC",
    odooEquivalent: "Spreadsheet / BI dashboards",
    industryRelevance: "S&OP et revue performance mensuelle.",
    demoGuidance: "Comparez plusieurs options stratégiques en démo.",
    evalGuidance: "Seuil 70/100 — qualité décision évaluée.",
    recoveryPaths: ["Revoir trade-offs stock/service/coût"],
    alternativeActions: [
      "Prendre une décision basée sur un seul KPI (ex. rotation seule) — ignore les trade-offs",
      "Ignorer l'arbitrage stock / service / coût dans la synthèse stratégique",
      "Formuler une recommandation sans justification liée aux KPI combinés",
    ],
    wrongActionConsequences: ["Décision sous-optimale → perte compétitivité"],
  },
  "SCN-015": {
    scenarioId: 15,
    scnCode: "SCN-015",
    objective: "Exécuter un cycle opérationnel intégré fournisseur → entrepôt → client.",
    context: "Simulation M5 complète : réception, rangement FIFO, inventaire, réappro, KPI et décision.",
    role: "Gestionnaire d'Entrepôt",
    module: "Integrated WM + IM + KPI",
    controlPoints: ["Chaque étape M5 validée", "Cohérence stock bout-en-bout", "KPI final conforme"],
    studentActions: ["M5_RECEPTION", "M5_PUTAWAY", "M5_CYCLE_COUNT", "M5_REPLENISH", "M5_KPI", "M5_DECISION", "COMPLIANCE_M5"],
    expectedOutcome: "Cycle intégré complété, conformité M5.",
    supervisorNotes: "Capstone opérationnel avant certification Gold.",
    technicalSpecs: { sku: "Multi-SKU", quantity: "Variable", suggestedBin: "REC → STOCKAGE → EXP" },
    successCriteria: ["7 étapes M5 complétées", "Conformité finale", "Score ≥ 70"],
    failureConditions: ["Écart non résolu", "Décision KPI incohérente"],
    wmsFunction: "End-to-end warehouse orchestration",
    sapEquivalent: "EWM integrated scenario",
    odooEquivalent: "Full warehouse workflow",
    industryRelevance: "Pilotage entrepôt omnicanal.",
    demoGuidance: "Parcourez le flux complet sans pression certification.",
    evalGuidance: "Chaque étape compte pour progression M5 et Gold.",
    recoveryPaths: ["Corriger écart inventaire avant décision"],
    alternativeActions: [
      "Clôturer COMPLIANCE_M5 avec un écart inventaire non résolu — KPI final faussé",
      "Sauter M5_REPLENISH ou M5_CYCLE_COUNT pour aller directement au KPI — flux incohérent",
      "Prendre M5_DECISION avant d'avoir complété les étapes opérationnelles amont",
    ],
    wrongActionConsequences: ["Incohérence flux → KPI final faussé"],
  },
  "SCN-016": {
    scenarioId: 16,
    scnCode: "SCN-016",
    objective: "Gérer des écarts d'inventaire en cours de simulation intégrée et appliquer corrections.",
    context: "Cycle M5 avec variance injectée — actions correctives requises avant clôture.",
    role: "Gestionnaire d'Entrepôt",
    module: "Corrective warehouse control",
    controlPoints: ["Variance détectée", "Correction avant KPI", "Traçabilité ADJ"],
    studentActions: ["Réception → Putaway → CC avec écart → Replenish → KPI → Decision → Compliance"],
    expectedOutcome: "Écarts corrigés, simulation clôturée conforme.",
    supervisorNotes: "Priorité : résoudre physique avant décision.",
    technicalSpecs: { sku: "Variable", quantity: "Variable", suggestedBin: "STOCKAGE" },
    successCriteria: ["Variance résolue", "Décision post-correction"],
    failureConditions: ["Compliance avec écart ouvert", "ADJ manquant"],
    wmsFunction: "Exception management",
    sapEquivalent: "MI07 in integrated flow",
    odooEquivalent: "Inventory adjustment wizard",
    industryRelevance: "Gestion exceptions temps réel en ops.",
    demoGuidance: "Rejouez la branche CC→ADJ en démo.",
    evalGuidance: "Correction obligatoire en évaluation.",
    recoveryPaths: ["CC → ADJ → reprise flux"],
    alternativeActions: [
      "Passer à M5_KPI sans corriger l'écart physique détecté au cycle count — décision erronée",
      "Valider COMPLIANCE_M5 avant l'ajustement ADJ requis — audit trail incomplet",
      "Ignorer la variance injectée et continuer le flux — stock système incorrect",
    ],
    wrongActionConsequences: ["Stock incorrect → décision KPI erronée"],
  },
  "SCN-017": {
    scenarioId: 17,
    scnCode: "SCN-017",
    objective: "Analyser les KPI globaux et formuler une décision stratégique justifiée.",
    context: "Capstone M5 : indicateurs agrégés après cycle ops — choix stratégique final.",
    role: "Directeur Logistique",
    module: "Strategic decision layer",
    controlPoints: ["KPI M5 analysés", "Décision alignée données", "Compliance finale"],
    studentActions: ["Compléter ops steps", "M5_KPI", "M5_DECISION", "COMPLIANCE_M5"],
    expectedOutcome: "Décision stratégique validée, conformité Gold-path.",
    supervisorNotes: "Niveau Bloom : Create — justification essentielle.",
    technicalSpecs: { sku: "Portfolio", quantity: "KPI aggregate", suggestedBin: "N/A" },
    successCriteria: ["Décision argumentée", "KPI cohérents", "Conformité M5"],
    failureConditions: ["Décision sans lien KPI", "Compliance prématurée"],
    wmsFunction: "Strategic warehouse decision support",
    sapEquivalent: "IBP / analytics tie-in",
    odooEquivalent: "Executive dashboard decision",
    industryRelevance: "Comité logistique direction.",
    demoGuidance: "Explorez options décision en mode démo.",
    evalGuidance: "Décision finale évaluée pour certification Gold path.",
    recoveryPaths: ["Revoir KPI puis reformuler décision"],
    alternativeActions: [
      "Formuler M5_DECISION sans lien aux indicateurs M5_KPI agrégés — décision non fondée",
      "Clôturer COMPLIANCE_M5 prématurément avant synthèse stratégique complète",
      "Recommander une orientation entrepôt sans données chiffrées du portefeuille KPI",
    ],
    wrongActionConsequences: ["Mauvaise orientation stratégique entrepôt"],
  },
};
